coding-test-java/problems

- .github/workflows/action.yml
- kimyeonsup/Test.java
> PR Reviewers test

- honghuipyo/ags/week1/RockFestival.java
- problems.iml
> 시간 복잡도 :  unknown, 공간 복잡도 : unknown
```
```
> [AGS] 록 페스티벌/ 1번 / 30분

- kimyeonsup/Test.java
- kimyeonsup/algospot/Boggle.java
- kimyeonsup/algospot/Festival.java
> 시간 복잡도 :  O(N* (N - L) * L), 공간 복잡도 : O(1)
N = 대여 가능일 수, L = 대여 일 수
문제를 간단하게 요약하면,  
```대여 가능일 수 = N, 팀 수 = L, 공연장 대여 비용 = Arr(N) ``` 이 주어지고, 대여 일 수는 `최소 한 팀당 하루`라고 하였을 때 공연장 대여 비용 최소 평균 값을 구하는 문제다.
**입력**
```
6 3
1 2 3 1 2 3 
```
해당 입력에 답은 `(1+2+3+1)/4 = 7/4` 으로 대여 일수가 늘어나더라도 최소 평균만 구하면 된다.
그렇기 때문에 `최소 대여 일수 = 팀 수`가 되고, 최소 대여 일수 ~ 최대 대여 가능 일 수까지 모든 경우의 수를 완전 탐색으로 합계 평균 값을 구한다.
- 해당 문제는 완전 탐색으로 쉽게 풀이할 수 있는 문제다.
- 하지만 탐색 과정에서 속도를 개선할 수 있는 방법이 있다.
- 합계를 구할 때 이전에 구했던 합계를 알고 있으면 다음 합계를 쉽게 구할 수 있다.
1. 위에 입력을 구한다 하였을 때
2. 처음은 `1 + 2 + 3 = 6` 이 되고,
3. 그 다음은 `6 - 1 + 1` 을 해주면 된다.
- `-1` = 맨 처음 인덱스 값, `+1` = 2,3,1 에서 마지막인 `1`이다.
- 코드에서 합계 최소 값을 구한다음 평균을 구했지만, 바로 평균을 계산하여 최소 평균을 구해도 별 차이가 없다. 오히려 최소 평균을 바로 구했다면 변수와 코드 길이가 약간 더 줄어든다.
- `double min = 1001` 은 101 이어도 됨
> 시간 복잡도 :  O(8^n), 공간 복잡도 : …
> 김연섭 / 1기 1주차 / 2문제

- kimyeonsup/baekjoon/Boj_3085.java
https://www.acmicpc.net/problem/3085
> 시간 복잡도 :  O(n^3), 공간 복잡도 : 
오프라인 모임에서 페어프로그래밍으로 다른 분과 같이 의논하면서 진행했다.
해당 문제는 완전 탐색 알고리즘으로 풀 수 있는 문제고, 역시나 탐색과정에서 시간 복잡도를 줄이면 시간초과 나지 않고 풀 수 있는 문제였다.
하지만 문제에서 제시하는 약간 까다로운 조건이 있어 탐색 내부 알고리즘을 생각하기가 쉽지 않은 문제였다.
문제를 작은 단위로 쪼개서 생각해보면 답을 구할 수 있다.
1. 각 행과 열의 연속된 사탕의 최대길이를 구한다. 어렵지 않게 생각할 수 있다.
2. 사탕 swap 후에 탐색해야되는 행과 열을 선택한다.
- swap 방향을 고려한다.
문제를 풀면서 생각지도 못한 곳에서 약간 복병이 있었다.
**Arrays.copyOf**
또 다른 하나는 자바 동작방식을 잘 생각하지 못한채 사용했던 Arrays.copyOf 메서드다.
2차원 배열일 경우 배열이 다른 배열의 주소값을 가지는 형태이기 때문에 해당 주소값이 복사된다. 그래서 깊은 복사가 제대로 되지 않는다.
그래서 swap할 때 기존 배열까지 같이 복사돼서 값이 제대로 나오지 않았다.
---
이번에 처음으로 페어프로그래밍 방식으로 코테 문제를 풀었다. 페어프로그래밍의 최대 장점은 나와 다른 관점을 알 수 있게 된다는 것이다.
내가 생각하는 방식과 전혀 다른 방식으로 문제를 접근하는 것을 보고, 많은 생각을 들게 했다.
그리고 문제를 풀 때 제각각 다른 코딩 스타일을 볼 수 있다.
1. 어떤 사람은 시간 복잡도 보다 코드의 가독성을 …
> 김연섭 / 1기 1주차 / 1문제 / 오프라인

- parkjaewoo/AGS/Week1/boggleGame2.java
- parkjaewoo/BOJ/Week1/Boj_3085.java
[오프라인] 사탕게임 - BOJ 3085번
시간 복잡도 O(N**3), 공간 복잡도
실행시간 : 252ms java 11
풀이
알고리즘은 구현, 완전 탐색을 이용했습니다.
대신, 분기점을 이용하여 max값을 찾을 때 board[x][y]에서 3줄의 탐색만을 고려하여 구현하였습니다.
인접한 글자와 바꾸는 경우의 수는 2가지 입니다.
1. 오른쪽과 왼쪽을 바꿀 경우 아래 두 번, 오른쪽 한 번을 탐색합니다.
2. 위와 아래를 바꿀 경우 아래 한 번 오른쪽 두 번을 탐색합니다.
> 박재우 / 1기 1주차 / 1문제 / 오프라인 

- yongjun/AGS/Week2/CandyGame.java
> 시간 복잡도 :  O(N^3) , 공간 복잡도 : 
```
완전 탐색과 구현을 이용해 풀었습니다.
1. 사용자의 입력 받은 값의 가장 긴 연속 부분을 구했습니다.
2. 완전 탐색을 통해 행, 열의 모든 사탕의 위치를 바꿔가며 가장 긴 연속 부분을 구했습니다. (같은 사탕은 제외)
3. 가장 긴 연속 부분의 길이를 출력했습니다.
```
```
사탕을 교환한 뒤, 가장 긴 연속부분을 구하는 것에만 신경을 써서 사용자가 사탕을 입력했을 때 초기 사탕의 가장 긴 부분을 구하지 못 했습니다.
반복문 중 바깥 반복문을 0 ~ n -1로 수행하였는데 이로 인해 마지막 행, 열을 구하지 못 했습니다.
```
---
페어프로그래밍을 하니 혼자 문제를 풀 때와는 달리 다양한 방법으로 접근할 수 있어서 좋았습니다.
> 홍용준/ 1기 1주차 / 1문제 / 오프라인

- yongjun/AGS/Week2/AGS/BoardCover.java
- yongjun/AGS/Week2/AGS/Picnic.java
- yongjun/AGS/Week2/BOJ/CandyGame.java
> 시간 복잡도 :  76ms, 공간 복잡도 : 
> 조건문을 통해 탐색의 횟수를 줄이는 것에 집중을 하였습니다.
```
1. 1부터 학생 수까지 반복하는 반복문을 통해 모든 학생이 짝이 되었는지 검사를 한다.
2. 모든 학생이 짝이 되었으면 1을 반환한다.
3. 한 명이라도 짝이 되지 않은 학생이 있으면 짝이 되지 않은 학생의 뒷 순서에 있는 학생들 중 짝이 가능한 학생을 찾는다.
4. 짝을 찾았으면 재귀 함수를 통해 새롭게 반복을 한다.
```
---
> 시간 복잡도 : 64ms , 공간 복잡도 : 
```
1. 블록이 움직일 수 있는 경우의 수를 4가지로 판단 후, 구현하였습니다.
2. 맨 위 왼쪽칸부터 탐색을 시작하였습니다.
3. 탐색을 하며, 비어있는 칸이 있으면 블록을 넣어보고 블록이 들어갈 수 있으면 색을 칠한 뒤, 재귀함수를 통해 반복하는 로직으로 구현하였습니다.
4. 비어있는 칸을 찾는 반복문은 소풍과 같은 방법으로 구현하였습니다.
```
---
```
1. 매일 코딩테스트를 공부했다. (디스코드 스터디 참여)
2. 문제를 정확히 이해한 뒤 문제를 해결하려는 습관이 생기기 시작했다.
```
```
1. 그래프 유형의 문제를 푸는데 어려움을 겪는다.
```
```
1. 백준 그래프 문제를 많이 풀어보자
2. 바킹독에서 그래프 관련 강의를 보자
```
> 홍용준 / 1기 2주차 / 2문제

- sanghwa/AGS/BoardCover.java
- sanghwa/AGS/ClockSync.java
- sanghwa/AGS/Picnic.java
- 1시간동안 풀이를 성공하지 못해 [블로그](https://steady-coding.tistory.com/174)를 참고했습니다.
```
1. 0번 학생부터 짝을 만들며 진행하여 중복된 경우의 수가 발생하는 걸 방지한다.
2. boolean값을 통해 이미 짝을 맺은 학생은 탐색에서 제외한다.
3. 재귀를 통해 (0,1) (0,2) (0,3)과 같은 모든 경우의 수를 탐색한다.
```
---
- 풀이는 책 참고 (p.161)
```
1. 역시나 중복된 경우를 제외하기 위해 왼쪽 상단부터 탐색을 시작합니다.
2. 실질적으로 놓을 수 있는 타일의 모양은 총 4가지
3. 기준 좌표에서 4가지 모양의 타일을 dy, dx를 이용해서 놓을 수 있는지 판단
4. 재귀적으로 모든 경우의 수를 탐색한다.
```
---
- 풀이는 책 참고 (p.168)
```
1. 재귀를 통해서 9번 스위치부터 한번 누르고 다음 스위치 재귀...
2. 4번을 누르면 원위치로 돌아오기 때문에 최대 4번만 누른다.
3. 모두 12시를 가리키면 경우의 수를 하나 증가
```
---
- 모든 문제를 스스로 해결하지 못했지만 완전탐색에 대해서 조금씩 알아갈 수 있었다.
- 클론코딩을 해보면서 문제 해결의 흐름을 따라가면서 이해할 수 있었다.
- 완전 탐색을 재귀로 하기 위한 기저케이스 판단, 큰 흐름을 제일 작은 단위의 흐름으로 만들어서 재귀함수를 작성해야 하는 능력 필요.
- 완전 탐색을 편하게 하기 위한 자료형판단 …
> 이상화 / 1기 2주차 / 3문제

- parkjaewoo/AGS/Week2/BoardCover.java
- parkjaewoo/AGS/Week2/BoardCover2.java
- parkjaewoo/AGS/Week2/ClockSync.java
- parkjaewoo/AGS/Week2/Picnic.java
문제명 : 소풍
시간 복잡도 : 164ms, 공간 복잡도 : O(N^2)
문제명 : Board Cover
시간 복잡도 : x, 공간 복잡도 : x
문제명 : Sync Clocks
시간 복잡도 : x, 공간 복잡도 : x
건의 사항
> 박재우 / 1기 2주차 / 2문제

- parkjaewoo/AGS/Week3/Fence.java
- parkjaewoo/AGS/Week3/Fence2.java
- parkjaewoo/AGS/Week3/QuadTree.java
- parkjaewoo/BOJ/Week2/Q2302.java
https://www.acmicpc.net/problem/2302
문제명 : 극장 좌석
시간 복잡도 : O(n), 공간 복잡도 : O(n)
1. 풀이 과정
dp를 통해 구현하였습니다.
결국 경우의 수를 어떻게 구할 것인가에 관한 문제였고, vip석을 기준으로 나누어 곱해주면 경우의 수에 도달할 수 있다는 것을 착안하여 해결하였습니다.
dp의 점화식 구조는 피보나치 수열과 동일합니다.
이후, vip의 idx를 기준으로 배열의 길이를 구합니다. 이 길이에 해당하는 dp[길이] 값을 구하고 이를 answer *= dp[길이]와 같은 방식으로 해결하였습니다.
다른 분들의 코드를 보니 vip[idx] || vip[idx - 1]을 건너뛰는 방법을 채택한 것 같습니다. 이 부분에 대해서는 아이디어가 바로 나오지 않았는데 더 쉽게 풀 수 있는 방법에 대해서 고민해보는 것이 중요하다고 생각했습니다.
다음 dp문제가 나온다면 더 효율적으로 풀 수 있는 방법을 고민해보겠습니다.
페어 프로그래밍
이상화 팀원과 같이 페어프로그래밍을 진행해보았습니다.
자바와 알고리즘을 잘 모름에도 구현에 대한 생각을 하는게 깊이가 있는 느낌이었고, 열심히 따라오다보면 실력이 많이 늘 것 같았습니다.
이번 페어프로그래밍을 통해 설계를 조금 더 꼼꼼히 해야겠다고 생각했습니다.
같이 문제에 접근하며 이건 어떨지, 저건 어떨지 서로의 생각만 공유하기 바빴고, 정작 시간복잡도를 먼저 계산하는 것과 같이 중요한 부분에는 신경을 못썼던 것 같습니다.
앞으로 코딩테스트 문제에 접근할 때는 시간복잡도에 먼저 접근을 하고 설계를 들어가야겠다는 생각을 했습니다. …
> [BOJ] 극장좌석 / 실버 1 / 30분

- kimyeonsup/algospot/Quadtree.java
- kimyeonsup/baekjoon/Boj_2302.java
https://www.acmicpc.net/problem/2302
> 시간 복잡도 :  O(n), 공간 복잡도 :  O(n)
이 문제는 dp로 접근하면 쉽게 풀 수 있는 문제였다. 문제에서 요구하는 답을 풀어내는 과정에서 규칙이 보이는 문제여서 쉽게 점화식을 유추하고 풀 수 있다. 하지만 완전탐색에 사로잡혀 다른 방식을 생각하지 못하고 결국 풀지 못했다. 완전탐색으로 답을 구할 수는 있다. 하지만 백준에 제출하면 시간초과로 통과할 수 없다. 문제를 읽고 요구사항을 잘 봤다면 dp로 생각할 수 있는 문제였다.
내가 세운 점화식은 다음 과 같다.
```
dp[i] = dp[i -1] + dp[i - 2]
```
햐지만 이것만으로는 풀 수 없다. 이유는 vip라는 고정석을 고려해야된다.
그래서 다시 한번 답을 하나씩 써가며 확인해보니,
vip 좌석이거나 그 전에 좌석이 vip일 경우, `vip == num || vip == num -1`
답이 그 전 dp 값과 같다는 것을 확인할 수 있다. 이유는
1 2 3 4 5
vip = 4
일 때, 4 5는 고정이 되버린다.
4는 vip이지만, 5는 좌석을 옮길 수가 없다. 그래서 숫자가 1 2 3 일 때와 동일한 값이 된다.
```
1 2 3 
1 3 2 
2 1 3
```
에서 숫자 4, 5 만 붙인 형태가 된다.
---
이번 오프라인 문제는 온라인 문제와 비슷해보여서 가져온 문제였다. 하지만 생각과 달랐다. 그래서 다른 스터디원도 나의 한마디에 완전탐색으로 생각이 고정됐다. 😂
그래도 교훈을 얻었다고 생각한다. 코테 문제를 풀 때는 숲을 보고 여러 고려사항을 잘 확인. …
> 김연섭 / 1기 2주차 / 오프라인

- yongjun/AGS/Week2/BOJ/TheaterSeat.java
> 시간 복잡도 : 120ms , 공간 복잡도 : 
**dp[n] = dp[n - 1] + dp[n - 2]**
```
재우님께서 오프라인때 말씀해주신 vip 좌석을 제외한 나머지 좌석들의 연속된 좌석의 가능한 경우를 구해 곱하는 방법으로 접근했습니다.
1. vip 좌석을 입력 받으면서 가장 긴 일반 좌석의 길이를 구했습니다.
2. 가장 긴 일반 좌석의 길이만큼 dp 계산을 반복 했습니다. (가장 긴 좌석의 길이 이상으로는 계산 할 필요가 없어서 이런 방식으로 구현했습니다)
3. 좌석의 길이만큼 dp 배열에서 가능한 경우를 구한 뒤, 곱했습니다.
4. 곱한 값을 출력했습니다.
```
> 홍용준 / 1기 2주차 / 오프라인

- honghuipyo/boj/week1/CandyGame.java
> 홍희표 / 1기 1주차 / 오프라인

- choidonghyeon/java/OFFLINE/BOJ/TheaterSeat.java
> 시간 복잡도 :  O(N), 공간 복잡도 : 
> 실행 속도 : 72ms
오프라인 끝나고 집에오면서 `DP`로 접근하니 구현 자체는 정말 간단했습니다.  물론 이 문제를 보고 `DP`를 떠올리는 것 자체가 어려운 것 같습니다.
문제에서 현혹될 만한 요소가 몇가지 있는 것같습니다. 예제의 그림을 보면
좌석번호 , 입장권 번호 , VIP 이런 단어들에 집중하다보면 미궁에 빠지기 쉬울 것 같습니다.
문제를 단순화 할 필요가 있었습니다. 문제의 텍스트에서 이런 말이 나옵니다.
<213465789> 와 <132465798> 는 허용되지 않는 배치 방법이다. 
이와 같이 숫자의 나열만으로 위 상황을 표현하는 것이 가능합니다. 따라서 N의 길이가 1일때부터 나열해보면 다음과 같습니다.
```
* VIP 가 0 일때 
- N = 1
1
---- N = 2
1 2
2 1
---- N = 3
1 2 3
2 1 3
1 3 2
---- N = 4
1 2 3 4
2 1 3 4
1 3 2 4
1 2 4 3
2 1 4 3
규칙성
---- N = 5
1 2 3 4 | 5
2 1 3 4 | 5
1 3 2 4 | 5
1 2 4 3 | 5
2 1 4 3 | 5
-> (N=4)일 떄의 경우에 5만 추가 되었음.
1 2 3 | 5 4
2 1 3 | 5 4
1 3 2 | 5 4
-> (N=3)일 때의 경우에 (5,4) 만 추가 되었음.
```
즉 위의 나열로 VIP가 존재하지 않을 때 점화식은
dp[n]= dp[n-1] + dp[n-2]
이며 여기서 이제 해야할 것은 VIP만 고려해주면 됩니다. 
+ n이 `vip`이거나
+ n-1 이 …
> 최동현/ 1기 2주차 / 1문제

- choidonghyeon/java/AGS/FANMEETING.java
- choidonghyeon/java/AGS/Fecne-Sweep.java
- choidonghyeon/java/AGS/Fence-BruteForce.java
- choidonghyeon/java/AGS/Fence-DivideConquer.java
- choidonghyeon/java/AGS/QuadTree.java
> 시간 복잡도 : O(N)
> 실행시간 : 64ms
이번주 7장의 주제는 **분할 정복**이였네요. 문제를 풀고나서 책을 보니 제 풀이는 **트리 자료구조**에 좀 치중하지 않았나 싶었습니다.
제 풀이의 과정은 두 단계로 나누어 집니다.
1. 문자열을 트리로 만들기.
2. 만들어진 트리를 상하 뒤집은 순서로 순회하기.
1번과정에서 트리를 구현할 때는 일반적인 트리 구현과 달리, 노드 클래스만 만들고 트리 클래스는 만들지않았습니다.
노드 클래스를 활용해서 충분히 문제에서 원하는 트리를(`그림 (b)`) 표현 할 수 있었기 때문입니다.
트리를 만들때는 재귀를 활용했고 책에서 설명하는 분할 정복과 유사합니다.
2번 과정에서는 기본적인 트리 순회를 이용하되, 자식 노드를 탐색하는 순서만 바꾸어
상하 뒤집기를 구현하였습니다.
*코드가 좀 난해할 수 있지만 최대한 주석을 달아놓았습니다.*
분할 정복과 비교하면 시간복잡도 상에서 조금 손해가 있습니다. 
+ N : 문자열의 길이 
+ 분할 정복 : O(N)
+ 제 코드 : O(2N) ==> 트리를 만들고, 순회해야했기때문에
다만, 실행시간이 `64ms`로 다른 코드들보다 빠르게 측정됐는데
이것은 단순히 최대길이가 1000이라는점과 `StringBuilder`로 최적화한 결과라고 생각됩니다.
---
> [완전탐색]
> 시간복잡도 : O(N**2) 
> 실행시간 : 1394ms
> 이외의 풀이인 분할정복과 스위핑은 해설과 다른사람의 풀이를 참고했습니다.
<ul>분할정복으로 풀어보려했으나 실패하여</ul> 완전탐색으로 해결했습니다. 
`N`이 최대 …
> 최동현 / 1기 3주차 / 3문제

- sanghwa/AGS/QuadTree.java
https://algospot.com/judge/problem/read/QUADTREE
```
1. 쿼드트리 class를 정의 했습니다.
2. 들어온 문자열을 순서대로 깊이우선탐색(DFS)으로 트리를 만들었습니다.
- 'x'를 만나면 노드를 생성하고 최대 4개의 자식노드를 생성합니다. 
- 이외 문자를 만나면 노드를 새로 만들고 리턴합니다.
- 결과적으로 'x'에 대해서 자식노드를 재귀적으로 생성합니다.
4. 만들어진 트리의 노드를 0 1 2 3 에서 2 3 0 1로 재귀적으로 상하 반전을 합니다.
5. 반전한 트리를 다시 깊이 우선 탐색으로 문자열을 만들어서 출력합니다.
```
- 쿼트트리의 재귀적 탐색의 탈출조건을 만들기 위해 isLeaf변수를 사용하여 맨 아래층 노드를 판단했습니다.
- 머리로는 어떤 구조와 흐름으로 가면 된다가 있는데 실제 구현으로 가는 과정이 쉽지않았습니다.
---
- 나머지 문제들은 감기때문에 몸상태가 좋지 않았어서 며칠을 날렸더니 남은 시간이 부족해서 시간안에 해결하지 못했습니다...
> 이상화 / 1기 3주차 / 1문제

- honghuipyo/ags/ags.iml
- honghuipyo/ags/week3/Fence.java
- honghuipyo/ags/week3/QuadTree.java
- honghuipyo/boj/boj.iml
- honghuipyo/boj/week1/CandyGame.java
> 홍희표 / 1기 3주차 / 2문제

- kimyeonsup/algospot/Fence.java
- kimyeonsup/algospot/Quadtree.java
https://algospot.com/judge/problem/read/FENCE
https://algospot.com/judge/problem/read/QUADTREE
> 시간 복잡도 :  O(4^n) , 공간 복잡도 :  O(1)
처음에 문제 예시에서 `xxwww bxwxw bbbww xxxww bbbww wwbb` 이 부분 때문에 헷갈렸다. 띄어쓰기는 왜 해놓은건지… 그리고 나서 문제를 이해한 후 함수 재귀 호출이 먼저 떠올랐다. 문제에서 x가 4분할을 표시하니 x 이후 4개의 알파벳을 먼저 상하로 바꿔야했고, x안에 또 분할할 수 있는 점을 봤을 때 이 문제는 재귀 함수였고, 문제 통과 시간과 복잡도 계산 후 충분히 풀 수 있겠다고 판단했다.
문제에서 그림은 상하로 바뀐다고 했다. 상하로 바뀌면 알파벳은 어떻게 바뀌는가?
1. x 이후에 문자 4개는 1 ↔ 3, 2 ↔ 4 서로 바뀐다.
2. 그러면 2번을 swap 해주면 되는데 입력이 그냥 문자열이라서 분할에서 담거나?, swap할 때 x이면 x안에 값들 까지 계산을 구현해야한다. 
번거롭다 생각했다. 그래서 어차피 재귀이니 swap말고 문자열을 새로 조합하기로 결정했다. 그렇게 생각하니 설계는 금방 할 수 있었다.
생각한 방법은 다음과 같다.
1. x이후에 4개의 값을 탐색할 때 3 → 4 → 1 → 2 순서로 탐색한다.
2. 해당 위치에 문자가 x이면 함수를 다시 호출한다.
3. x가 아니면 StringBuffer에 문자를 추가한다.
4. 조합 된 문자를 toString() 하여 return한다.
5. 반복
그런데 구현에서 좀 애먹었다. 간과했던 …
> 김연섭 / 1기 3주차 / 2문제

- yongjun/AGS/week3/IceBerg.java
> 시간 복잡도 : 2628ms , 공간 복잡도 : 
```
빙산 문제는 DFS와 탐색으로 해결할 수 있었습니다.
1. 인접한 0의 개수를 구해야함
인접한 0의 개수만큼 빙산을 녹여야 합니다.
이때 빙산의 위치를 저장하는 리스트를 생성한 뒤, 리스트의 크기만큼 반복하며 주변 0의 개수를 계산하는 로직으로 구현하였습니다.
(완전 탐색으로 구현함)
2. 빙산이 몇 덩어리인지 구해야함
빙산이 녹아 두 덩어리 이상이 되면 반복을 중지한 뒤, 빙산이 녹은 년수를 출력하는 문제였습니다.
이때 dfs로 빙산을 한번 탐색한 뒤 (visited 배열을 통해 방문 유무를 구분함), 빙산이 저장된 리스트를 순회하며 방문하지 않은 빙산이 발견되면 
년수를 출력한 뒤 끝냈습니다.
```
---
> 홍용준 / 1기 3주차 / 오프라인

- kimyeonsup/baekjoon/Boj_2573.java
https://www.acmicpc.net/problem/2573
> 시간 복잡도 :  O(n^2) , 공간 복잡도 : 
한 덩어리의 빙산이 주어질 때, 이 빙산이 두 덩어리 이상으로 분리되는 최초의 시간(년)울 구해야하는 문제
이번 문제는 구현과 그래프를 활용한 문제였다.
문제 요구사항을 정리해보면
1. 빙산을 녹인다.
2. 녹은 후 빙산이 두덩어리로 나누어지는 확인한다.
- 빙산이 녹는다면 0을 출력
1. 빙산을 녹인다.
빙산을 녹이는 방법은 빙산의 테두리인 0을 기준으로 구현하면 된다. 빙산을 기준으로 탐색하면 빙산이었지만 녹아서 없어져버린 빙산을 체크해야하기 때문에 추가적으로 구현해야한다. 빙산은 동시에 녹기 때문이다.
2번 같은 경우는 dfs로 어렵지 않게 풀 수 있다. 그리고 추가적으로 빙산이 동시에 모두 녹아버리는 예외 사항을 잘 체크하면 문제는 통과된다. 문제를 풀 때는 해당 조건을 구현하지 못해 while문이 끝나지 않게 됐고, 시간 초과가 났다.
요구사항을 잘 정리하고, 주어진 사항에 대한 구현 방식을 잘 설계하면 어렵지 않게 풀 수 있는 문제였다. 하지만 페어프로그래밍을 하면 다른 사람과의 대화에 집중을 하게되 요구사항 까먹게 되면서 문제를 풀 수가 없었다. 더군다나 문제를 잘 정리한 편도 아니었다. 그래서 이번 페어에서는 요구사항을 잘 정리해야고, 디테일한 설계의 중요성을 다시 한번 깨달았다. 또한, 구현은 했지만 다른 문제로 인해 어려움에 빠지게 됐다면(디버깅이 잘 안돼서 문제 파악이 안되면) 문제를 처음 부터 다시 한번 정리해봐야한다. 이 부분도 나는 잘 안됐던 것 같다.
> 김연섭 / 1기 3주차 / 오프라인

- parkjaewoo/AGS/Week4/JumpGame.java
- parkjaewoo/AGS/Week4/Lis.java
- parkjaewoo/AGS/Week4/TrianglePath.java
- parkjaewoo/AGS/Week4/WildCard.java
시간 복잡도 : , 공간 복잡도 :
```
오른쪽 및 아래로 가는 것을 체크하는 과정 + visited처리를 통해 dfs로 구현하였습니다.
```
```
결과값이 Yes or No뿐이라 가능한지만 체크하기에 n <= 100이지만 가능하다고 생각했습니다.
동적계획법으로도 풀어보아야 겠습니다.
```
시간 복잡도 : , 공간 복잡도 :
```
체크했던 문자인지 확인하는 과정을 -1 (아직 비교 안함), 0 (불가능), 1 (가능)로 두고 dp를 활용하여 풀었습니다. (처음에는 구현으로 해결해보려했지만 못풀고 풀이를 참조하였습니다)
재귀를 통해 해당 문자에 저장된 값이 -1이라면 조건문에 의해 wildName과 fileName을 비교합니다.
문제는 '*' 문자열이었고, '*'일 경우에는 wildName에 +1을 한 재귀값, fileName에 +1을 한 재귀값을 비교하여 가능한 방향을 찾습니다.
```
```
dp를 공부해보면 할 수록 단순 점화식으로 풀 수 있는 느낌이 아닌 재귀, 메모이제이션, 구현이 합쳐진 것 같다는 느낌이 듭니다.
이런 문제를 만났을 때는 구현을 방점으로 찍고, 메모이제이션을 섞을 수는 없을지, 재귀를 섞을 수는 없을지 고민해보는 습관이 중요한 것 같습니다.
```
시간 복잡도 :O(N^2) , 공간 복잡도 :
```
2중 for문을 사용하여 각 index값에서 왼쪽 위 값, 바로 위 값을 통해 dp를 사용하여 풀었습니다.
```
```
유명한 dp문제인 것 같습니다. 해당 문제를 풀어본 경험이 있어 쉽게 해결하였습니다.
```
시간 복잡도 : , 공간 복잡도 :
```
아직 풀지 …
```
> 박재우 / 1기 4주차 / 3문제

- choidonghyeon/java/AGS/JumpGame.java
- choidonghyeon/java/AGS/LIS.java
- choidonghyeon/java/AGS/TrianglePath.java
- choidonghyeon/java/AGS/WildCard.java
```
1. 방문 기록을 체크하는 dp 테이블을 생성한다.
2. 방문하지 않은 칸에대해서만 오른쪽과 아래로만 진행하는 dfs를 실시한다.
3. 방문한 칸에대해서는 dp를 true로 초기화한다.
4. 끝지점에 도달했다면 true를 반환한다.
```
총평: dp초기화 하는 시점이 헷갈렸지만 전체적으로는 간단했습니다.
---
* 완전 탐색 , 구현 느낌으로 풀었습니다. *
```
1. 와일드카드에서 '*'이 두 개이상 연속 되는 부분을 '*'로 치환한다. ('*'이 두개 이상 연속이면 사실상 '*'과 같으므로)
2. 와일드카드와 타겟의 단어를 검사하는 메서드를 실행한다.
3. 와일드카드의 문자를 for문으로 돌때, '*'일때 '*' 다음글자가 '?'이거나 현재 word의 탐색중인 글자와 같다면 재귀로 다시 메서드를 실행한다.
```
총평 : dp로 접근해보려다 쉽지 않아서 그냥 문자열, 구현 느낌으로 풀었습니다. 하지만 머릿속으로 잘 그려지지 않아서 시행착오를 겪으면서 코드를 완성했습니다. 그것때문인지 코드자체가 조금 난잡해진 감이 있습니다.
---
```
1. 이중 포문으로 우하향의 방향으로 인덱스를 진행한다.
2. 각 칸은 위와 왼쪽 대각선의 칸을 통해서만 이동해 올 수 있으므로 두개의 칸 중 더 긴 경로를 선택하여 현재 칸의 value를 더한다.
3. dp테이블의 마지막행에서 가장 큰 값을 구한다.
```
총평 : 점화식 자체가 너무나 간단하게 세워져서 쉽게 풀었던것 같습니다. …
> 최동현 / 1기 4주차 / 4문제

- kimyeonsup/algospot/JumpGame.java
- kimyeonsup/algospot/Lis.java
- kimyeonsup/algospot/TrianglePath.java
- kimyeonsup/algospot/Wildcard.java
> 시간 복잡도 :  O(n^2), 공간 복잡도 : 
어렵지 않게 풀 수 있었고, 탐색할 수 있는 모든 경로를 탐색하고 메모이제이션을 활용하여 풀이한다.
1. 기저사례를 확인한다.
2. 탐색방향인 오른쪽, 아래를 탐색할 수 있게 다시 재귀호출한다.
3. 탐색한 좌표에 대해서 방문 처리를 하여 중복 탐색을 막는다.
---
> 시간 복잡도 :  O(n^2), 공간 복잡도 : 
와일드 카드가 풀이를 생각하기가 어려웠다. 완전 탐색으로 풀이할 수 있으나 dp로 풀기에는 생각하기가 어려웠다. 그래서 책을 참고하면서 풀었다.
dp로 푸는 방식은 탐색해야될 CASE를 확인해서 재귀호출을 하고, 탐색결과에 대한 값을 dp에 저장하는 방식이다.
함수는 매개변수로 두 문자열의 문자를 비교하기 위해 인덱스 값을 받는다.
**CASE**
1. 와일드카드 문자와 탐색 문자열의 문자가 같거나 와일드 카드 문자가 '?' 일 경우
2. 두 문자열의 index가 문자열의 길이와 같을 경우 -> 탐색이 끝까지 갔다면
3. 와일드 카드 문자가 '*'일 경우
**dp에 저장되는 값은 다음과 같다.**
-1 : 아직 탐색하지 않음
0 : 탐색했으나 와일드카드와 일치하지 않음
-1 : 탐색했고 와일드카드와 일치
책에서 봤던 알고리즘 복잡도는 O(n^2)이나 다른 책에서 나온 for문을 활용한 풀이 방식은 O(nlogn)까지 줄일 수 있다고 한다.
---
> 시간 복잡도 :  O(n^2), 공간 복잡도 : 
dp문제를 조금 풀어봤다면 해당 문제와 같은 유형은 접하지 않았을까? 이 문제와 아래에 LIS는 알고리즘을 이해하기 위한 기초문제라고 생각이 …
> 김연섭 / 1기 4주차 / 4문제

- kimyeonsup/algospot/JLis.java
- kimyeonsup/algospot/Pi.java
- kimyeonsup/algospot/Quantization.java
풀수가 없어서 책을 보면서 공부한다는 생각으로 문제를 풀었다. 책에서 나온 풀이과정은 다음과 같다.
1. 수열 A,B를 앞에서 부터 숫자 하나씩 선택하여 둘 중 큰 값을 선택한다. max
2. 선택한 값을 수열 A, B에 있는 나머지 값들과 비교한다.
-  max값과 비요하여 max가 더 작으면 재귀 호출하여 다음 index 번호를 넘겨준다.
점화식
jLis(indexA, indexB) = max (max(jLis(indexA, nextB) + 1, jLis(nextA, indexB) + 1);
여기서 다음 을 만족하는 경우만 재귀호출을 한다.  `max < 수열[index]`
---
이번 문제도 책을 보고 문제 풀이를 했다. 백트래킹으로 자리수 조합을 생각하고 dp로 중복 탐색을 제거해야겠다는 생각까지 했지만
구현을 어떻게 할지 생각을 못했다. 그래서 책을 보면서 구현했다. 풀이방식은 유사하나 구현에서 막힌 문제였다.
풀이방식은 다음과 같다.
1.  자리수 조합이란
-> 333, 334, 335 ..... 553, 554, 555
2. 333이라하면
3. 1 ~ 3 부분 수열을 가지고 난이도를 구한다.
4. 그리도 다음 자리수를 구하기 위한 재귀호출을 한다.
5. 둘의 값을 합친 값을 result와 비교하여 최대 값을 저장한다.
3. 구한 result 값을 dp에 저장하고 재귀호출시 dp값을 활용해서 탐색한 값이면 그 값을 반환하여 중복 탐색을 막는다.
---
완전 탐색으로 모든 …
> 김연섭 / 1기 5주차 / 2문제

- yongjun/AGS/week4/JLIS.java
1. 아침 알고리즘 스터디를 꾸준히 했다.
1. 설 연휴가 지난 뒤, 알고리즘 공부를 조금 안 했다...
2. 4 ~ 5주차 문제를 제대로 풀지 않았다.
3. 아직 알고리즘을 판단하는데 조금 미숙한 감이 있다.
1. 다음주부터 다시 정신을 차려서 문제를 잘 풀어야겠다.
**ps. 차주부터는 다시 열심히 참여하겠습니다.. 다들 파이팅!!**
> 홍용준 / 1기 5주차 / 1문제

- honghuipyo/ags/week6/Snail.java
- honghuipyo/ags/week6/Tiling2.java
- honghuipyo/ags/week6/TripathCnt.java
```
```
---
```
```
---
```
```
> 홍희표 / 1기 6주차 / 3문제

- yongjun/AGS/week6/Snail.java
- yongjun/AGS/week6/Tiling.java
- yongjun/AGS/week6/Tripathcnt.java
> 시간 복잡도 : O(N) , 공간 복잡도 : 
```
cache[n] = cache[n - 1] + cache[n - 2]라는 점화식을 발견한 뒤 
c의 범위인 1부터 100까지의 경우를 전부 구하고 해당 배열을 출력했습니다.
```
---
> 시간 복잡도 : 220ms , 공간 복잡도 : 
```
큰 문제를 해결하기 위해 작은 문제를 호출하는 탑-다운 방식으로 해결하였습니다.
2차원 배열을 두 개 생성해 하나의 배열에는 연산 값을 저장하고 나머지 하나에는 경로를 저장하였습니다.
연산을 계산할 때는 Math의 max 함수를 이용해 움직일 수 있는 두 개의 경우의 수를 비교한 뒤, 더 큰 값을 더하도록 구현하였습니다.
```
---
> 시간 복잡도 : O(N) , 공간 복잡도 : 
```
cache[height][days] = 0.75 * dp(height + 2, days + 1) + 0.25 * dp(height + 1, days + 1);
위 식을 통해 달팽이가 움직일 수 있는 경우를 cache에 저장했고, cache 배열의 값 유무를 확인해 메모리제이션을 진행하였습니다.
```
> 홍용준 / 1기 6주차 / 3문제 

- parkjaewoo/AGS/Week6/Tiling2.java
- parkjaewoo/AGS/Week6/TriPathCnt.java
> 시간 복잡도 : O(n)  , 공간 복잡도 :
dp의 가장 기초적인 문제인 것 같습니다.
2*n 타일링의 경우 피보나치 수열이 생성된다는 것을 염두하고 풀었습니다.
실제로 주어진 n의 경우인 1과 5를 대입해보고 확신이들어 바로 구현하였습니다.
---
> 시간 복잡도 : O(n^2) , 공간 복잡도 :
경로의 max값을 찾는 문제의 응용 버전이라고 생각합니다.
먼저 max값을 찾는 과정을 dp로 짠 다음, 문제 풀이 설계를 들어갔습니다.
중요한 것은 경로에 대한 값 또한 dp로 해결해야된다는 것이었습니다.
3차원 배열을 쓰고 싶었는데, 익숙하지 않아 pathBoard라는 경로에 대한 dp 2차원 배열을 하나 더 생성하였습니다.
시간이 좀 있다면 다음에는 3차원 배열에 대해서도 깊이 고민해봐야겠습니다.
---
> 시간 복잡도 :  , 공간 복잡도 :
자격증 공부를 진행하고 있어 부득이하게 풀지 못했습니다. 다른 분들의 코드를 보고 배워보겠습니다.
---
> 박재우 / 1기 6주차 / 2문제

- parkjaewoo/BOJ/Monitor.java
- parkjaewoo/BOJ/TurnOnOff.java
- parkjaewoo/PGS/WordRelay.java
```
알고리즘 유형은 구현이라고 생각합니다.
남자와 여자의 상황에 따라 다른 함수를 만들어 구현하였습니다.
남자의 경우 스위치를 단순히 약수로 나누어주면 되었지만, 여자의 경우는 조금 더 효율적인 방법에 대해 고민했던 것 같습니다.
또한, 출력 상황 같은 부분들을 체크하지 않아 바로 맞추지 못했습니다. 이런 부분 또한 신경써야겠습니다.
```
---
```
한글자씩 비교하며 4가지 분기로 답을 도출해냈습니다.
단순 리스트를 이용하여 해결하였는데, map이나 set을 쓰신 분이 많아 이러한 방법으로도 해결해봐야겠다고 생각했습니다.
```
---
```
dfs와 5가지 타입을 함수로 만들어 해결하였습니다.
동작 방식이 엄청 까다로운 것 같지는 않지만, 코드가 점점 길어지면서 헷갈리기도 하고, visited처리를 하지 않기 위해서 매개변수로 board를 전달해보기도 하면서 많이 배운 것 같습니다
특히, 시간 복잡도 적으로 가능하겠다 생각하고 구현해보았는데 결국 해결할 수 있어서 좋았던 경험 같습니다.
```
> 박재우 / 2기 1주차 / 3문제

- youngwoo/BOJ/BOJ_1244.java
- youngwoo/PGS/PGS_wordchain.java
```
남학생과 여학생 함수를 따로 분류하였습니다. 그리고 학생 수만큼 반복하며 gender에 따라 male 또는 female 함수를
호출하게 하였습니다. 스위치 상태 반전하는 코드는 정답을 참조하였고 보기 더 편하게 구현할 수 있었습니다.
cf. https://stackoverflow.com/questions/21706345/what-does-mean-in-java-001
```
---
```
이 문제는 2명 이상의 사람이 차례대로 단어를 말하며, 마지막 사람이 단어를 말하지 못하거나
틀린 단어를 말하면 탈락하는 게임입니다. 이 문제는 주어진 단어 리스트를 기반으로 탈락자가
발생하는 순서를 계산하는 문제입니다.
1.알고리즘 설계
for문을 통해 주어진 단어 리스트를 순회합니다.
각 단어에 대해 탈락 조건을 검사합니다.
탈락 조건에 해당하는 경우 탈락자 정보를 answer 배열에 저장하고 for문을 종료합니다.
for문을 종료한 후 탈락자가 발생하지 않았을 시 answer 배열에 [0,0]을 저장합니다.
```
---
```
CCTV의 모든 경우의 수를 탐색하여 사각지대를 계산하려고 하였습니다. 
5가지 종류의 CCTV 각각에 대해 가능한 방향 조합을 모두 고려하려고 하였습니다. 
다만 단점이 시간 복잡도가 높아 불필요한 경우의 수를 탐색하지 않게 하기 위해 코드를 작성하려 하였으나 구현이 복잡하여 완성하지 못하였습니다.
```
---
> 임영우/ 2기 1주차/ 3문제

- kimyeonsup/baekjoon/Boj_1244.java
- kimyeonsup/baekjoon/Boj_15683.java
- kimyeonsup/programmers/WordChainGame.java
> 시간 복잡도 :  O(n*count), 공간 복잡도 : 
- 성별과, 주어진 번호에 따라서 스위치 변경 방식을 구현하면 문제를 풀 수 있는 간단한 문제였습니다.
- 그래서 남자,여자에 따른 스위치 변경 방식을 그대로 구현했습니다.
---
> 시간 복잡도 : O(n), 공간 복잡도 : 
- 영어 끝말잇기를 구현하면 되는 문제입니다.
1. 이미 나왔던 단어일 경우
2. 이전 단어와 끝 알파벳과 현재 단어 맨 앞 알파벳이 다를 경우
3. 주어진 단어가 모두 끝났을 경우
1. 출력해야 하는 값을 구하기 위해서 사용하는 `number`, `personalNumber`가 반복문 로직상 어디에 위치해야하는 지 헷갈렸음.
---
> 시간 복잡도 : O(4^n), 공간 복잡도 : 
1. 백트래킹으로 CCTV 방향 조합을 모두 탐색하여 풀었습니다.
2. 제시된 CCTV 요구사항을 잘 구현하면 백트래킹으로 어렵지 않게 풀 수 있습니다.
1. CCTV를 어떻게 구현해야할까 고민을 많이 했습니다.
2. 고민하다 추상 클래스를 사용하여 구현했습니다.
3. 이유는 디버깅하기 편할 것 같아서 입니다. 코드가 길어져 구현 시간이 오래걸린다고 해도 후에 디버깅 하기는 쉬었습니다. 그래서 오타난 부문 또는 엣지케이스를 쉽게 잡을 수 있었던 것 같습니다.
1. 후에 다른 사람들의 코드를 봤을 때 사각지대 값을 구하는 곳에서 `벽과 CCTV를 뺀 총 개수` - `CCTV에 감시 되는 개수`를 하면 반복문을 하지 않아도 쉽게 구할 수 있다는 것을 알았습니다.
- 변수명 잘 짓기
- 쉽게 생각하기
- 주석 달기
- 주석 달기가 잘 안됨
- …
> 김연섭 / 2기 1주차 / 3문제

- yongjun/first/Week1/Boggle.java
- yongjun/first/Week1/RockFestival.java
- yongjun/first/Week2/AGS/BoardCover.java
- yongjun/first/Week2/AGS/Picnic.java
- yongjun/first/Week2/BOJ/CandyGame.java
- yongjun/first/Week2/BOJ/TheaterSeat.java
- yongjun/first/week3/FanMeeting.java
- yongjun/first/week3/Fence.java
- yongjun/first/week3/IceBerg.java
- yongjun/first/week3/QuadTree.java
- yongjun/first/week4/JLIS.java
- yongjun/first/week6/Snail.java
- yongjun/first/week6/Tiling.java
- yongjun/first/week6/Tripathcnt.java
- yongjun/second/week1/English.java
- yongjun/second/week1/Switch.java
- yongjun/second/week1/Watch.java
```
1. 여성과 남성을 따로 구분하여 문제를 진행하였습니다.
2. 남성의 경우 배수이기 때문에 배수와 인덱스를 비교해 진행하였습니다.
3. 여성의 경우 두개의 포인터를 이용해 범위를 구했습니다.
4. StringBuilder를 이용해 값을 출력했습니다.
```
---
```
1. checkWord, ValidateWord라는 함수를 이용해 비교, 중복 검사를 진행하였습니다.
2. 통과한 횟수가 단어의 길이와 같다면 모두 정답을 말한 것으로 간주하고 0,0을 넣었습니다.
3. 그 외 경우에서는 실패한 인덱스를 찾은 뒤, answer에 넣는 형식으로 구현하였습니다.
```
```
인덱스를 0으로 강제하다 보니, 인덱스가 1부터 시작하는 문제에서는 강제로 + 1을 해주는 번거로운 작업이 필요했습니다.
인덱스를 1로 해서 구현을 해야겠다라는 생각을 하였습니다.
```
---
```
1. 1 ~ 5까지의 CCTV가 방향에 따라 감시할 수 있는 방향을 배열로 저장했습니다.
2. 지도를 입력받을 때 CCTV들을 List안에 저장했습니다.
3. 모든 CCTV가 동서남북을 보는 경우의 수를 계산해 최소값을 출력합니다.
```
> 홍용준 / 2기 1주차 / 3문제

- sanghwa/BOJ/Cctv.java
- sanghwa/BOJ/Switch.java
- sanghwa/PGS/EnglishWordRelay.java
```
WomanAct 부분에서 현재 idx의 +1, -1 씩 움직이면서 두 idx의 value가 같은 상태이면 스위치의 변환을 진행했습니다.
스위치의 변화에는 0, 1 사이의 변화이기 때문에 XOR 비트연산을 사용하여 구현했습니다.
마지막 출력에 20개씩 개행을 넣어서 출력해야하는 부분을 읽지 못하고 15분정도 시간을 더 사용하긴 했습니다...
```
---
```
프로그램이 끝나는 조건은 총 3가지였습니다.
1. 앞에 단어의 끝 문자와 다른 문자로 시작
2. 이미 앞에 사용한 단어 사용
3. 끝까지 완료
String의 charAt 메서드를 사용하여 끝문자와 시작문자를 비교하였습니다.
checkOverlap 함수를 사용하여 처음부터 현재 인덱스의 단어 까지 비교하여 검사했습니다.
최존적으로 끝난 상태를 간단한 수식으로 유도하여 저장한 후 반환하였습니다.
```
---
```
dfs로 시도 하였으나 너무 많은 시간을 사용하고 제출할 정도의 완성을 하지 못하여 코드는 없습니다.
```
[바킹독 시뮬레이션](https://blog.encrypted.gg/948)
해당 링크의 정보를 참고하여 추후에 해결하여 올려보겠습니다!
> 이상화 / 2기 1주차 / 3문제

- yongjun/second/week1/Pizza.java
```
오븐의 크기를 줄이는 과정이 핵심인 것 같습니다.
min 함수를 이용해 오븐의 크기를 줄인 뒤, 
while (length > 0 && array[length] < pizza) {
반복문을 이용해 피자가 위치를 찾아가도록 구현하였습니다.
```
---
> 홍용준 / 2기 1주차 / 오프라인

- kimyeonsup/baekjoon/Boj_1756.java
https://www.acmicpc.net/problem/1756
기존에 풀이 했던 TreeMap으로는 풀 수 없던 문제였습니다. 이유는 `pizzaDia 보다 작은 값들 중 가장 빠른 값 (가장 위에 있는 값)`을 구해야 하기 때문인데, TreeMap.lowerKey는 할 수 없었습니다.
그래서 다른 풀이를 참고하여 풀었습니다. 풀이 방법에는 `이진 탐색 방법`과 단순하게 그리디로 푸는 방법이 있었습니다. 올린 구현 코드는 그리디 방식으로 탐색할 때 맨 안쪽(인덱스 탐색을 맨 위부터 아래로)부터 탐색합니다. 그러면 복잡도가 O(n)까지 가지 않아 시간 초과가 나지 않는다는 걸 알 수 있습니다.
이 문제도 너무 복잡하게 생각하지 않았다면 금방 풀 수 있지 않았나 생각들 만큼 풀이를 보면 약간 허무감이 들었던 것 같습니다. 그런데 그만큼 어려웠던 문제 같습니다.
---
> 김연섭 / 2기 1주차 / 오프라인

- choidonghyeon/java/BOJ/1756_피자굽기.java
오프라인에서 풀지 못했지만, @jaewoopk , @YongGoose 님이 설명해주신 내용에서 아이디어를 얻고 고민후에 풀어봤습니다.
```
1. 위에서 아래 방향의 오븐의 최소 지름을 미리 누적으로 구한다.
2. 피자를 순서대로 밑에서부터 위로 올리며 가능한 오븐을 차례대로 탐색한다.
```
구현문제이지만 완전히 하드코딩 느낌의 빡구현 문제는 아니며, 처음에는 시간복잡도를 생각해야하고 그다음엔 아이디어를 떠올리는 과정이 필요해서 어렵지 않았나 싶습니다. 개인적으로 구현 문제치고 생각할 것이 많은 좋은 문제라 생각되네요..
> 최동현 / 2기 1주차 / 오프라인

- parkjaewoo/BOJ/SecondWeek1/Monitor.java
- parkjaewoo/BOJ/SecondWeek1/TurnOnOff.java
- parkjaewoo/BOJ/SecondWeek2/FindMine.java
- parkjaewoo/BOJ/SecondWeek2/Matrix.java
- parkjaewoo/PGS/SecondWeek1/WordRelay.java
- parkjaewoo/PGS/SecondWeek2/JoyStick.java
> 시간 복잡도 :  O(n*m), 공간 복잡도 : 
문제의 3x3 부분 행렬이라는 말에 혼동이와 오래 걸린 문제입니다. (3x3 행렬 내의 부분 행렬이라는 말로 오해했습니다)
결국 3x3 행렬에 대해 전체적으로 다 뒤집어 B와 같이 만들면 되는 문제입니다.
문제에서 불가능한 경우의 수가 나오면 -1을 출력하는 원리 및 다른 부분이 나오면 무조건 뒤집어야 하는 원리를 이용해 풀었습니다.
전체 행렬을 탐색하고 A와 B의 요소가 다르면 무조건 뒤집는 방식을 취했습니다.
---
> 시간 복잡도 : O(t*n) , 공간 복잡도 : 
먼저 지뢰를 찾고 이를 빼준 뒤, 어디에 있는 지 모를 지뢰의 개수를 찾는 문제입니다.
지뢰수가 최대가 되는 것을 문제에서 요구했지만, 사실 불가능한 경우의 수가 없으면 지뢰수는 최대거나 최소거나 정확한 수가 나오게 됩니다.
지뢰의 개수는 전체 합 / 3을 기준으로, 만약 전체 합 % 3 == 0 이라면 +1, 아니라면 지뢰의 갯수를 놔두면 됩니다.
---
> 시간 복잡도 :  O(n), 공간 복잡도 : 
처음에 2번째 인덱스에 'A'가 있을 경우만 예외처리 해주는 문제인 줄 알고 틀린 뒤 오래 고민해본 문제입니다.
다른 분의 Math.min 로직을 참고하였습니다. 제가 푼 문제가 아니기에 별다른 설명은 달지 않겠습니다.
---
> 박재우 / 2기 2주차 / 3문제

- kimyeonsup/baekjoon/Boj_1080.java
- kimyeonsup/baekjoon/Boj_9082.java
- kimyeonsup/programmers/Pgs_JoyStick.java
> 시간 복잡도 :  O((n-3) * (m-3)), 공간 복잡도 : 
그리디 알고리즘을 공부하고, 풀이를 참고했습니다.
그리디 알고리즘은 각 단계에서 가장 최적이라고 생각되는 것을 선택해 나가면서 답을 구하는 방식이다. 여기서 최적의 값을 값을 보장하는 것이 아닌 가장 답과 가까운 근사한 값을 목표로 한다.
- 선택 절차 : **이 단계에서는 ‘현재 상태’에서 ‘최적인 선택’을 합니다.** 이 선택은 이후에는 바뀌지 않습니다.
- 적절성 검사 : **이 단계에서는 선택한 항목이 ‘문제의 조건’을 만족시키는지 확인합니다.** 조건을 만족시키지 않으면 해당 항목은 제외됩니다.
- 해답 검사: **이 단계에서는 모든 선택이 완료되면, ‘최종 선택’이 ‘문제의 조건을 만족’시키는지 확인합니다.** 조건을 만족시키면 해답으로 인정됩니다.
선택 절차 : A[r,c] 부터 3x3까지 0→1로 바꾼다.
적절성 검사 : 뒤집은 후 A가 B와 같다면 횟수 추가하고 다음을 검사
해답 검사: 연산의 최소 횟수 값을 반환한다.
행렬을 연산해서 바꿀 때 겹치는 범위가 있고 겹치지 않아서 한 번만 연산하게 되는 경우가 있습니다. 또한 연산은 0,1로만 이루어져 있기 때문에 행렬 값이 달라서 연산을 했다면 다시 또 연산을 할 필요가 없습니다. 그래서 인덱스 r,c라 했을 때 A[r,c] == B[r,c]일 때는 연산을 할 필요가 없습니다.
---
> 시간 복잡도 :  O(n), 공간 복잡도 : 
ABC 라는 알파벳이 주어졌을 때 최소 조작 횟수를 구하는 문제입니다. 알파벳은 주어진 문자열의 길이에 맞춰서 모든 알파벳이 A로 …
> 김연섭 / 2기 2주차 / 3문제

- choidonghyeon/java/BOJ/1080_행렬.java
- choidonghyeon/java/BOJ/9082_지뢰찾기.java
문제의 조건 중에서 3X3사이즈 행렬만 뒤집을 수 있다는 점에서 뒤집을 3x3행렬의 (0,0)을 기준으로 목표로 하는 행렬과 비교하여 뒤집을지 말지를 선택했습니다. 또한 각 칸마다 뒤집힌 횟수를 따로 기록하였습니다.
만약 뒤집을 수 없는 경우 (ex)최초 5x5행렬에서 현재 (4,2)를 탐색하는 경우)에서 이때까지 뒤집힌 횟수를 고려하여 현재 상태를 구하고 이것이 목표로 하는 행렬과 다르다면 -1을 반환하였습니다.
---
주어진 문제 자체가 일렬로 나열된 형태에서 지뢰를 찾으라고 말을 하고 있으므로, 고려할 사항이 굉장히 줄었다고 생각됩니다.
결국 i번째의 근처 지뢰의 갯수는 i-1, i , i+1의 지뢰 갯수와 같습니다. 
따라서 반복문으로 차례대로 위처럼 3개씩 지뢰의 유무를 정해 나가면 답을 찾을 수 있습니다. 이때 처음과 끝의 경우 각각 오른쪽, 왼쪽처럼 하나의 지뢰만 인접하므로 이경우를 위해 총지뢰 배열의 사이즈를 2만큼 늘여서 앞뒤로 빈공간을 추가해서 코드를 간편하게 작성했습니다.
---
문제를 이해하고 접근 자체는 그리디하게 했으나 최종적으로 구현을 실패했습니다.
> 최동현 / 2기 2주차 / 2문제 

- yongjun/second/week2/JoyStick.java
- yongjun/second/week2/Mine.java
- yongjun/second/week2/Procession.java
> 시간 복잡도 : O(N * M) , 공간 복잡도 : 
```
두 개의 배열을 저장한 뒤, 이중 반복문을 통해 다른 값이 있으면 첫 번째 배열에 있는 3X3 크기의 원소를 뒤집는 방법으로 구현하였습니다.
그리디 문제였지만 완전 탐색으로 문제를 해결한 것 같습니다..
```
---
```
지뢰가 첫 번째 인덱스에 있을 때, 마지막 인덱스에 있을 때, 그 외의 경우 
이렇게 3가지로 상황을 나눠서 구현하였습니다.
3가지 경우로 나눈 이유는 각각 지뢰가 있다고 판단을 했을 때 숫자를 다르게 줄여야 하기 때문에 분리했습니다.
지뢰가 발생할 수 있는 상황이면 지뢰가 있다고 판단한 후, 인접한 숫자를 줄였습니다.
문제를 해결한 후, 알고리즘 분류를 보니 에드훅이 있어서 왜 에드훅인지 찾아봤는데 공식이 있었습니다...
(에드훅 PTSD 오네요)
```
---
```
1. 알파벳을 효율적으로 설정하는 방법
A - N, O - Z 이렇게 구간을 설정해 효율적으로 알파벳을 설정했습니다.
2. 위치를 효율적으로 설정하는 방법
위치를 효율적으로 설정하기 위해서는 정방향뿐만 아니라 역방향으로도 탐색할 수 있어야 합니다. 예를 들어, "BAAAAB"를 살펴보면, 정방향으로 탐색하면 5번을 이동해야하지만 역방향으로 가면 1번만 가면 되는 것을 알 수 있습니다.
또한, "BBBBAAAABA"와 같이 처음부터 역방향으로 가야 효율적으로 설정할 수 있는 경우도 고려해야 합니다. 이 경우에는 "BBBBAAAABA"에서 B -> BB -> BBB -> …
```
> 홍용준 / 2기 2주차 / 온라인

- youngwoo/BOJ/BOJ_1080.java
- youngwoo/BOJ/BOJ_9082.java
```
이 문제는 3x3 크기의 행렬을 뒤집어 두 개의 행렬을 동일하게 만들 수 있는 최소 변화 횟수를 계산하는 문제입니다.
1. 두 개의 배열을 비교:
입력으로 받은 두 개의 행렬 A와 B를 비교합니다. 만약 행렬 크기가 3x3 미만이면 두 배열을 직접 비교하여
동일한지 확인합니다. 행렬 크기가 3x3 이상이면 다음 단계로 진행합니다.
2. 3x3 서브 행렬 뒤집기:
두 배열을 순회하며, 각 요소를 비교합니다. 만약 두 요소가 다르다면 해당 요소를 포함하는 3x3 서브 
매트릭스를 뒤집습니다.
3. 최소 변화 횟수 계산:
위 과정을 반복하며 두 배열이 동일해질 때까지 변화 횟수를 계산합니다. 만약 두 배열을 동일하게 
만들 수 없다면 -1을 출력합니다.
```
---
```
이 문제는 2xN 크기의 지뢰 찾기 게임에서 지뢰의 개수를 찾는 문제입니다.
테스트 케이스 개수를 입력 받습니다. 그리고 각 테스트 케이스마다 숫자 문자열을 입력 받습니다.
숫자 문자열을 순회하며 각 자리의 숫자 값을 합산하고, 숫자 개수를 3으로 나눈 값에 2를 더하여 평균을 계산합니다.
숫자들의 합과 평균을 출력합니다.
```
---
```
인덱스를 구하여 문제가 나올 때 식을 계산하는 부분이 어려워 결국 구현을 하지 못하였습니다.
우선 상하로 움직이는 부분까지는 괜찮았습니다. A부터 움직이는 방법과 Z부터 뒤로 움직이는 방법 중 작은
값을 구하면 됩니다. 좌우 인덱스 이동하는 부분에 막혀 문제가 발생하였습니다. 연속되는 A의 개수를 구해서
좌우 중 어디로 움직이는 것이 이득일지 선택하면 될 것 같은데 더 고민해볼 문제인 것 …
```
> 임영우 / 2기 2주차 / 2문제

- kimyeonsup/baekjoon/Boj_15681.java
- kimyeonsup/baekjoon/Boj_2583.java
- kimyeonsup/programmers/TravelRoute.java
> 시간 복잡도 :  O(n^2), 공간 복잡도 : 
영역 구하기 문제는 dfs로 풀었습니다. DFS/BFS 알고리즘을 알고 있다면 쉽게 풀 수 있는 문제였던 것 같습니다.
넓이를 구할 때는 dfs가 호출 될 때마다 +1 되도록하고 탐색이 종료되면 List에 추가하도록 했고, 개수는 맨 처음 dfs를 호출할 때마다 하나식 증가하여 구했습니다.
---
> 시간 복잡도 :  O(n), 공간 복잡도 : 
트리와 쿼리 문제는  미리 각 노드 마다 정점의 개수를 저장을 하는 방식으로 풀었습니다..
가장 상위 루트 번호가 주어집니다. 그래서 주어진 노드와 간선들을 List에 모두 저장하고, DFS 탐색하여 정점의 개수를 배열에 모두 저장합니다.
그런 다음 정점의 개수를 미리 저장한 배열에서 주어진 쿼리 번호에 맞는  값을 가져오면 됩니다.
---
이번 문제는 다른 사람 코드를 참고해서 풀었습니다. 문제를 봤을 때 `모든 도시를 방문할 수 없는 경우는 주어지지 않습니다.`라고 잘못된 루트는 없을 거라고 생각하여 단순히 정렬된 값들을 탐색했지만, 그렇지 않았습니다. 
문제에서 가능한 경로가 2개 이상일 경우 알파벳 순서라고 했지만 우선이 되는 알파벳 순서로 가는 경로 중에 모든 티켓을 사용하지 못하는 경우가 생깁니다. 그래서 해당 문제는 완전탐색으로 풀어야 했습니다.
그래서 백트래킹 방식으로 문제를 풀었습니다.
---
> 김연섭 / 2기 3주차 / 3문제

- yongjun/second/week3/TravelRoute_failed.java
- yongjun/second/week3/TravelRoute_success.java
- yongjun/second/week3/boj_15681.java
- yongjun/second/week3/boj_2583.java
```
Node라는 클래스를 만들어 BFS를 구현해 쉽게 풀었던 것 같습니다.
2차원 boolean 배열을 생성해 탐색해야 하는 부분을 구분했으며, bfs를 호출한 횟수, bfs안에서 재귀 호출된 횟수로 count, size를 구했습니다.
```
---
```
문제 설명에 워낙 설명이 잘 되어있어서 따라하는 것 만으로도 쉽게 풀 수 있는 문제 같습니다.
다만 문제에 있는 의사 코드를 그래도 하면 시간 초과가 나서 
if (size[node] != 0) {
위의 조건문을 통해 메모리제이션을 구현하여 시간 복잡도를 줄였습니다.
```
---
```
처음 문제를 확인했을 때 "이게 왜 3단계지? 라는 생각을 했습니다"
하지만 주어진 항공권은 모두 사용해야 한다는 조건을 고려하지 않고 단순히 이름의 첫 문자를 비교해 DFS를 수행하는 방법으로 문제를 구현해 틀렸습니다. 
정답을 참고해 백 트래킹 방법을 사용해 문제를 풀었습니다.
```
> 홍용준 / 2기 3주차 / 3문제

- choidonghyeon/java/BOJ/TreeAndQuery15681.java
- choidonghyeon/java/BOJ/영역구하기2583.java
- choidonghyeon/java/PGS/여행경로_level3.java
주어지는 입력의 직사각형을 크기에 맞게 마킹만 제대로 한다면 그 다음부터는 쉬운 문제인 것 같습니다.
다만 입력에서 주어지는 좌표가 2차원배열의 인덱스와 일치하지않기 때문에 이것에 주의해야 할 것 같습니다.
마킹을 하고나면 마킹되지않은 부분을 기준으로 dfs를 진행하여 리스트에 추가했습니다.
---
문제 자체만 읽었을때는 이해가 잘안가지만 밑의 힌트를 보면 그래프 관련 용어 설명과 함께 이문제에서 힌트를 확인할 수 있습니다.
`R`로 주어지는 루트노드에서부터 dfs를 진행하며 각 정점에서 서브트리에 속한 정점의 수를 `dp`로 전부 업데이트를 실시합니다. 이렇게하면 주어진 쿼리에 대해서 O(1)의 시간에 답을 할 수 있습니다.
트리와 dp가 결합된 형태의 문제라고 생각됩니다.
---
문제에서 핵심은 결국 모든 간선(티켓)을 포함하는 경로를 어떻게 얻어 낼것인가였습니다.
문제를 어찌저찌 풀고 나서보니 대부분 사람들이 dfs+백트래킹 조합으로 쉽게 풀어낸것을 확인할 수 있었습니다.
저 같은 경우 백트래킹을 생각하지 못하고, bfs + 완전탐색 느낌으로 접근했습니다. queue를 사용하는 과정에서 경로와 사용한 티켓을 복사하는 작업이 있어서 효율성 측면에서는 많이 떨어지는것 같습니다.
> 최동현 / 2기 3주차 / 3문제

- youngwoo/BOJ/BOJ_16401.java
- youngwoo/BOJ/BOJ_6236.java
- youngwoo/PGS/PGS_Immigration.java
```
과자를 하나 이상 나눠줘야 하므로 최소 길이는 1, 모든 과자를 하나의 과자로 만들 수 있기에 최대 길이는
모든 과자의 길이의 합으로 설정했습니다. 현재 탐색 길이를 mid라 하고, mid 길이의 과자를 조카들에게
나줘줄 수 있는지를 canDivide()함수를 이용하여 판별했습니다. 나줘줄 수 있다면 더 긴 과자를 나눠줄 수 있는 
가능성을 생각하여 최대 길이를 mid로 갱신, 탐색 범위를 [mid+1, 최대길이]로 설정합니다. 나눠줄 수 없다면
탐색 범위를 [최소 길이, mid-1]로 설정합니다.
```
---
```
문제 이해를 못하여 정답을 참조하였습니다. 탐색 범위 최솟값을 left, 탐색 범위의 최댓값을 right로 설정합니다. 탐색 범위의 
중간값 mid를 계산합니다. mid 시간 안에 모든 입국자가 처리될 수 있는지 확인합니다. 처리 될 수 있다면 answer를 mid로 
업데이트 합니다. 탐색 범위 최댓값을 mid-1로 설정합니다. 처리될 수 없다면 탐색 범위의 최솟값을 mid+1로 설정합니다.
탐색 범위의 최솟값 left가 최댓값 right보다 작거나 같을 때까지 이분 탐색을 반복합니다. 반복이 끝난 후 answer로
모든 입국자가 처리될 수 있는 최소 시간을 반환합니다.
```
---
---
```
"과자 나눠주기" 문제와 비슷하게 접근하였습니다. 다만 코드가 계속 오류가 떠서 정답을 참조하여 오류를 찾아
냈습니다. 최소 인출 금액을 minWithdrawl, 최대 인출 금액을 maxWithdrawl로 설정합니다. minWithdrawl은 최소한 가장 큰
지출을 감당 할 수 있어야 …
```
> 임영우 / 2기 3주차 / 3문제

- parkjaewoo/AGS/SecondWeek4/Immigration.java
- parkjaewoo/BOJ/Week4/Q16401.java
```
최소 과자길이 1부터 최대 과자길이의 범위 안에서 이분탐색을 진행합니다.
countPossible이라는 함수를 따로 빼어 sum에 snack / value를 진행합니다.
이를 조카의 수와 비교하여 start와 end를 갱신합니다.
```
---
```
과자 나눠주기와 비슷한 접근으로 해결하였습니다.
최소 인원과 최대 인원을 start와 end에 넣고 isPossible이라는 함수를 따로 빼어 value / time을 sum값에 더해갑니다.
만약 return값이 n보다 크거나 같을 때, answer = mid, end = mid - 1로 갱신합니다.
다만, Long.MAX_VALUE가 안되고 sort후 times[times.length - 1] * (long)n을 end값으로 주어야만 테스트케이스에 통과합니다.
왜그런지는 리뷰나 오프라인 때 물어보고 싶습니다.
```
---
```
몸상태가 너무 좋지 않아 다 풀지 못하였습니다. 
```
> 박재우 / 2기 4주차 / 2문제

- kimyeonsup/baekjoon/Boj_16401.java
- kimyeonsup/baekjoon/Boj_6236.java
- kimyeonsup/programmers/ImmigrationScreening.java
> 시간 복잡도 :  O(logN), 공간 복잡도 : 
이진 탐색 구현 방법을 알고 탐색해야할 값(mid) 검증 로직만 생각하면 어렵지 않게 풀 수 있습니다.
mid는 조카 1명에게 나눠줄 수 있는 막대 길이입니다.
그렇기 때문에 주어진 각 막대들의 길이를 mid와 나눈 몫을 모두 더하면 해당 길이에서 총 몇명의 조카에게 나눠줄 수 있는지 알 수 있습니다.
---
> 시간 복잡도 :  O(logN), 공간 복잡도 : 
용돈 관리 문제도 비슷했습니다. mid값을 검증하는 부분에서 조금 오래 걸린 것 같습니다.
여기서 탐색하게 되는 값은 하루에 인출할 수 있는 금액입니다. 그래서 금액을 하루에 사용하는 days[] 배열을 순회하여 계산합니다.
```
if (amount < days[i]) {
int withCnt = days[i] / mid;
if (days[i] % mid > 0) withCnt++;
amount = mid * withCnt;
count += withCnt;
}
amount -= days[i];
// count >= mid -> 밑에서 count와 mid를 비교합니다.
```
1. days[i] / mid 값을 하여 하루 인출 횟수를 구합니다.
2. 인출 횟수 * mid하여 amount(현재 남아있는 금액)에 저장합니다.
3. 인출 횟수를 count에 더합니다.
4. amount에서 사용금액을 뺍니다.
```
5 5
1
1
1
1
100
```
반례인데 위 로직으로 하게 되면 count 값은 2가 나옵니다 하지만 문제에서 
`정확히 M번을 맞추기 위해서 남은 금액이 그날 사용할 금액보다 …
> 김연섭 / 2기 4주차 / 3문제

- yongjun/second/week4/과자_나눠주기.java
- yongjun/second/week4/용돈관리.java
- yongjun/second/week4/입국심사.java
> 시간 복잡도 :  log(n), 공간 복잡도 : 
```
이진 탐색을 통해 값을 탐색하며 모든 조카들에게 줄 수 있는 과자의 길이를 구하였습니다.
어려웠던 점은 없었던 것 같습니다.
```
---
> 시간 복잡도 :  log(n), 공간 복잡도 : 
```
문제를 이해하는데 애를 먹었습니다.
그러나 메인 로직은 과자 나눠주기 문제와 동일하게 이진 탐색으로 수를 구하면서 횟수를 비교하는 것으로 동일했습니다.
```
---
> 시간 복잡도 :  log(n), 공간 복잡도 : 
```
생각 없이 비교 횟수를 int 형으로 반환했다가 고생했습니다.
최대값이 10억이 넘으면 자료형을 신경써서 해야 할 것 같다는 생각을 했습니다.
이진 탐색을 통해 모든 사람들이 심사를 받는데 최소 시간을 구하였습니다.
```
> 홍용준 / 2기 4주차 / 3문제

- yongjun/second/week5/boj_1261.java
- yongjun/second/week5/boj_1916.java
- yongjun/second/week5/boj_4485.java
```
출발 지점부터 마지막 지점까지 우선순위큐와 BFS를 이용해 풀었습니다.
```
---
```
다익스트라 알고리즘을 활용해 구현했습니다. 
```
---
```
다익스트라 알고리즘을 활용해 구현했습니다. 
```
> 홍용준 / 2기 5주차 / 3문제

- kimyeonsup/baekjoon/알고스팟.java
- kimyeonsup/baekjoon/젤다.java
- kimyeonsup/baekjoon/최소비용구하기.java
> 시간 복잡도 :  O(nlogn), 공간 복잡도 : 
- 다익스트라로 문제를 해결했습니다.
- 다익스트라는 시작점 부터 각 정점까지 최단거리를 갱신하는 알고리즘 입니다.
- board는 그래프로 보고 벽을 가중치로 판단하여 풀이를 진행했습니다.
---
> 시간 복잡도 :  O(nlogn), 공간 복잡도 : 
- 위에 문제와 비슷했습니다. 다익스트라로 문제를 풀었습니다. 다익스트라 알고리즘을 알면 충분히 풀 수 있는 문제라 따로 설명은 안하겠습니다.
---
> 시간 복잡도 :  O(nlogn), 공간 복잡도 : 
- 다익스트라 알고리즘으로 풀었습니다. 3문제 전부 다익스트라 기본 문제였던 것 같습니다.
---
> 김연섭 / 2기 5주차 / 3문제

- choidonghyeon/java2/boj/알고스팟_0_1_BFS.java
- choidonghyeon/java2/boj/알고스팟_다익스트라.java
- choidonghyeon/java2/boj/젤다.java
- choidonghyeon/java2/boj/최소비용구하기.java
가장 간단한 해결 방법은 인접 행렬을 구성하여
출발 지점 부터 마지막지점까지 다익스트라 알고리즘을 사용하여 해결 할 수 있습니다.
하지만 이 문제에서 그래프의 가중치가 특별히 0과 1로 이루어져있기때문에 Deque 자료구조를 활용하는
`0-1 BFS`라는 알고리즘을 사용할 수도 있습니다.
이때는 우선순위큐를 활용할때보다 시간복잡도가 더 낮습니다.
---
인접리스트를 구성해서 다익스트라를 진행하였습니다.
---
인접행렬을 구성해서 다익스트라를 진행하였습니다.
> 최동현 / 2기 5주차 / 3문제

- sanghwa/BOJ/AlgoSpot.java
- sanghwa/BOJ/FindTheMinimumCost.java
- sanghwa/BOJ/TheOneInGreenIsZeldaRight.java
```
다익스트라 알고리즘과 bfs에 대한 지식이 부족하여 최종적으로 블로그를 참고하였습니다.
1. 처음 Vector와 LinkedList등 자료구조를 많이 사용해서 그런지 답은 구해지나 메모리 초과가 발생했습니다.
2. 간소한 자료구조 활용과 Queue에 넣는 조건 설정을 적절히 하여 메모리와 성능 개선을 해야한다는 점을 배울 수 있었습니다.
```
---
```
1번 문제와 같은듯 약간 다른 느낌을 받아 최종적으로 다시 블로그를 참고하였습니다.
1. Node 클래스를 만들고 compareTo 를 오버라이딩하여 우선순위큐를 사용할 수 있다는 점을 배웠습니다.
```
---
```
앞선 문제들의 학습을 통해 스스로 빠른 시간안에 구현할 수 있게 되었습니다.
1. 큐에 add하지 않는 조건을 설정하지 않아 무한루프를 경험했습니다.
2. 큐에 전부넣어버려서 메모리초과를 경험했습니다.
3. 큐에 넣을 때 현재 들어있는 비용보다 작아지는 경우만 큐에 넣어서 개선할 수 있었습니다.
```
---
> 이상화 / 5주차 / 3문제

- leeYuSung/BOJ/BOJ15685.java
- leeYuSung/BOJ/BOJ19238.java
- leeYuSung/BOJ/BOJ2146.java
1. 먼저 좌표,방향, 세대를 갖는 calss인 Node 클래스를 구현하였습니다.
2. 세대에 맞는 모양을 갖기 위해 solve 함수를 구현하여 세대가 올라가는 좌표를 list에 추가하였습니다
3. 이 문제의 규칙은 다음 세대가 이전 세대의 방향을 역순으로 받는 다는 것이었습니다. 이를 문제에 적용하기 위해 list에 추가할 때 list.add((list.get(j)+1)%4); 이러한 형식으로 추가하였습니다.
4. 모양이 완성되면 그 안에서 사각형을 찾는 함수인 find를 구현하였습니다  네개의 좌표가 모두 true이면 사각형이라 하였습니다.
---
1. 너비 우선 탐색(BFS)를 이용하여 섬을 식별하는 함수인 identifyIsland를 구현하여 섬마다 고유의 번호를 부여하였습니다.
2. 그 후 섬 간의 다리를 구현하는 함수인 findBridge를 구현하였습니다. 이 함수도 BFS를 활용하여 구현하였습니다.
3. main 함수에서 먼저 섬을 구분한 후 가장 짧은 다리를 구했습니다
---
1. 먼저 연료,행,열을 요소로 갖는 Taxi 클래스, 고유 번호, 해,열을 요소로 갖는 Clinet 클래스를 구현하였습니다.
2. 가장 가까운 승객을 찾아주는 find함수를 구현하였습니다. find 함수는 BFS를 활용하여 최단 거리를 찾는 함수인데 만약 거리가 같다면 행->열 순으로 구하는 조건도 추가하였습니다
3. 그 후 목적지까지 갈 수 있는지를 묻는 destination 함수를 …
> 이유성/3기 1주차 / 3문제

- junhyeong/week-1/src/BOJ15685.java
- junhyeong/week-1/src/BOJ19238.java
- junhyeong/week-1/src/BOJ2146.java
| 시간 복잡도 : , 공간 복잡도 :
1. 풀이 과정
100 * 100 2차원 배열을 만들고 드래곤 커브가 지나간 곳에 arr[i][j] = 1 로 만들어서 나중에 배열을 탐색하며 사각형이 만들어지는 곳을 찾고자 했습니다. 
드래곤 커브는 이전 방향(0, 1, 2, 3)에 +1 이 되는 패턴이 있었습니다. 그래서 여태까지 드래곤 커브의 방향을 history에 담고 그것을 거꾸로 읽으면서 (t + 1) % 4 하여 다음 드래곤 커브를 만들어서 풀었습니다.
| 시간 복잡도 : , 공간 복잡도 :
1. 풀이 과정
bfs를 두번 사용했습니다. 처음엔 섬마다 번호을 붙여주기위해 사용하고 두번째로는 섬끼리의 가장 가까운 거리를 구하기위해 사용하여서 풀이하였습니다.
| 시간 복잡도 : , 공간 복잡도 :
1. 풀이 과정
findCandidates에서 bfs를 사용하여 가장 가까운 승객을 찾습니다. 이때 연료가 다 떨어질때까지 찾지 못하면 실패처리 했습니다.  Collections.sort 를 사용해서 값이 같을 경우  거리->행->열 순으로 정렬했습니다. 그리고 손님위치로 택시를 옮기고 목적지 까지도 bfs를 사용해서 이동합니다. 
이러한 방법으로 손님 수인 m번 반복해서 반복문이 끝까지 된다면 성공이므로 남은 연료 energy를 출력합니다.
> 박준형 /3기 1주차 / 3문제

- kimyeonsup/baekjoon/DragonCurve.java
https://www.acmicpc.net/problem/15685
다른 사람 풀이를 참고해서 문제를 풀었습니다. 다시 복기하며 풀이 방식을 설명하겠습니다.
1. 1X1 크기인 정사각형의 네 꼭지점이 드래곤 커브의 일부인 개수를 구하는 조건은 해당 좌표가 1 또는 0으로 판별할 수 있습니다.
즉, 드래곤 커브를 구해서 직접 좌표를 1로 바꿔준다면 쉽게 구할 수 있습니다.
드래곤 커브가 만들어지는 과정을 보면 규칙성을 찾을 수 있습니다.
n세대 드래곤 커브를 만들 때  커브의 방향은 n-1세대 드래곤 커브 의 방향을 역방향으로 90도 돌린 것을 알 수 있습니다.
그렇기 때문에 커브 한 칸의 방향을 알 수 있습니다. 
그래서 `getDirections` 메서드에서 그 방향들을 `List`에 담아서 `map`에 그릴 수 있도록 구현된 것을 볼 수 있습니다.
---
변명이겠지만, 이번 주에는 다른 일들로 문제를 제대로 풀지 못했습니다. 반성하고 다음 주에는 다 풀 수 있도록 하겠습니다.
> 김연섭 / 3기 1주차 / 1문제

- yongjun/third/week1/boj_15685.java
- yongjun/third/week1/boj_2146.java
```
블로그를 참조하여 문제를 풀었습니다.
1. 방향을 d_list에 추가한다.
2. d_list에 있는 방향들을 마지막부터 뽑으면서 반시계 방향으로 한번 돌린 것을 다시 d_list에 추가한다.
3. d_list에 있는 방향들을 따라서 map[y][x]를 true로 설정한다.
4. map에서 네 점이 true 이면 카운트한다.
```
---
```
섬을 저장할 때 구분하는 것이 가장 중요한 것 같습니다.
bfs를 이용해 구분해서 저장을 한 뒤,  섬에서 다른 섬으로 가는 거리를 bfs를 이용하여 구했습니다.
```
---
하고 있는 작업에 시간을 너무 많이 투자해서 이번주는 문제를 다 못풀었네요...
다음주에는 3문제 다 풀겠습니다.
> 홍용준 / 3기 1주차 / 2문제

- choidonghyeon/java2/boj/다리만들기_2146.java
- choidonghyeon/java2/boj/드래곤커브_15685.java
> pr이 늦어서 죄송합니다! 마지막문제는 시간이 부족해서 풀지 못했습니다. 코드 리뷰는 오늘 저녁 쯤 올리겠습니다!
좌표폄면에서 회전에대한 기본적인 이해가 필요해서 조금 오래 걸렸던 것 같습니다.
최종적인 풀이는 좌표의 시계방향으로 90도 회전시 변하는 규칙을 찾아내고, 기준점을 이동했을때의 좌표 규칙을 반영하여 코드로 정의한뒤에 모든 드래곤커브를 만들어 냈습니다.
구현문제 중 이문제 처럼 회전의 개념을 적용하는 문제가 많았던것 같은데 이번에 확실히 배운것 같습니다.
---
이문제는 크게 두가지 부분문제로 생각할 수 있었는데요 
첫번째는 그룹핑으로 여기서는 `dfs`로 해결했습니다.
두번째는 최단 거리 건설인데 
처음 문제를 풀땐 `bfs`로 진행하다가 다른 대륙이 도달할시 현재 노드에서 건설할 수 있는 최단거리의 다리로 생각하여
모든 노드에서 탐색하는 식으로 하여 정답에 도달하긴했지만 이렇게 했을경우 같은 다리를 반복해서 찾아내는 비효율이 발생하더라구요.
이부분에서는 문제풀이 후 다른 분의 풀이를 참고해서 시간복잡도를 줄일 수 있었습니다. 최종적으로 처음풀이시 `272ms` 시간 복잡도 개선 후, `148ms`까지 줄일 수 있었습니다.
로직에 대해선 글로 설명하기 힘들것같아, 코드를 봐주시거나 설명이 필요하면 내일 질문주십쇼! 한주동안 고생많으셨습니다.!
---
> 최동현 / 3기 1주차 / 2문제

- sanghwa/BOJ/DragonCurve.java
https://www.acmicpc.net/problem/15685
```
1. 리스트에 방향값을 추가합니다.
2. 세대가 진행되면 역순으로 새로운 방향을 추가합니다.
3. 시작점을 시작으로 방향값에 따라 x, y값을 더해 map에 표시합니다.
4. 4점이 모두 표시된 수를 구하여 결과를 출력합니다.
```
---
새로 시작한 프로젝트때문에 일정관리를 실패하여 나머지를 풀지 못했습니다.ㅠ
다음주 부터 일정관리를 빡세게 해서 다 풀도록 하겠습니다!
> 이상화 / 3기 1주차 / 1문제

- sanghwa/BOJ/Task.java
- sanghwa/BOJ/WordMath.java
```
최대힙을 사용하여 점수가 가장높은 Node부터 계산합니다.
boolean 배열을 이용해서 day에 이미 과제를 수행했는지 확인합니다.
이미 과제를 했다면 1씩 감소하며 진행하지 않은 날짜를 찾아 계산합니다.
```
---
```
블로그를 참고 했습니다.
각 단어의 위치에 10의 제곱수로 계산하여 가중치를 구합니다.
가중치가 가장 큰 문자부터 9..8..7순서로 곱하여 최종 값을 구합니다.
```
---
> 이상화 / 3기 2주차 / 2문제

- choidonghyeon/java2/boj/과제.java
- choidonghyeon/java2/boj/단어수학_1339.java
- choidonghyeon/java2/boj/수열의_점수_2036.java
```
1. 기본적으로 음수와 양수를 리스트 형태로 구분해서 저장하고, 0 존재여부를 파악한다. 또한 1의 경우에는 바로 answer에 +1 한다.
2. 양수 리스트를 오름차순, 음수를 내림차순으로 정렬한후 리스트의 끝에서부터 2개씩 제거해나간다.
3. 리스트가 홀수개 일시 한개가남으므로 처리한다. 음수의 경우 0이 있으면 무효화시킨다.
```
---
```
1. 입력받은 과제를 점수를 기준으로 내림차순 정렬한다.
2. 과제들을 순회하며 마감일에 할당한다.
3. 해당일자에 이미 해당된 과제가 있을 시 마감일을 하루 씩 앞당겨가며 할당 가능여부를 조사한다. 
```
---
> 풀이를 참고 했습니다.
```
1. 주어진 단어에서 각 문자를 자릿수를 기준으로 10의 제곱을 해준다.
2. 가장 큰 숫자를 가진문자부터 9에서 0까지 할당한다.
3. 계산한다.
```
> 최동현 / 3기 2주차 / 3문제

- kimyeonsup/baekjoon/과제.java
- kimyeonsup/baekjoon/단어수학.java
- kimyeonsup/baekjoon/수열의점수.java
각 단어의 자리는 숫자의 자릿수를 의미 합니다.
가장 큰 자릿수를 가진 알파벳이 큰 숫자를 가지면 풀 수 있습니다.
```
ABC
DEF
```
A = 100, B = 10, C = 1
D = 100, E = 10, F = 1
각 알파벳이 가지는 자릿수 총합은 위와 같고, 큰 숫자 순서대로 정렬를 해준 뒤 알파벳에 9~0까지 숫자를 곱해서 합계를 구하면 됩니다.
---
처음에는 힌트 보고 헷갈렸으나, 가장 큰 점수가 합계에 포함되어야한다는 것을 알았습니다.
그리고 마감일을 고려햐여 마감일이 뒤에 있는 과제는 그만큼 여유가 있다는 뜻이니 뒤 늦게 수행하면 된다고 생각했습니다.
즉, 가장 큰 숫자이나 마감일이 여유롭다면 그 마감일에 수행하면 됩니다. 가장 큰 점수를 먼저 해당 마감 일에 배치하는 방식으로 문제를 풀었습니다.
---
음수와 양수를 나누어서 우선순위 큐에 담아서 문제를 풀었습니다.
양수 큐는 내림차순으로 음수는 오름차순으로 정렬되게 합니다.
그런 다음 두 큐 모두 하나만 남을 때 까지 두 정수를 곱해주고, 마지막 하나는 더하는 방식으로 풀었습니다.
하지만, 하나의 조건을 고려하지 못했는데 양수 큐에서 숫자가 1 일 경우 입니다. 만약 숫자가 1이면 곱하는 것보다 더해야 max를 구할 수 있기 때문에 양수 숫자가 1일 경우만 고려하면 문제를 풀 수 있습니다.
---
> 김연섭 / 3기 2주차 / 3문제

- junhyeong/week-2/src/BOJ13904.java
- junhyeong/week-2/src/BOJ2036.java
```
문제를 봤을 때 어떻게 묶어야 최대합을 구할 수 있을지 생각했습니다. 그렇게 내린 결론대로 구현했습니다.
1. 절댓값이 큰 음수두개를 묶어서 둘의 곱을 더하기
2. 남은 음수는 0이 있다면 0과 묶어서 내보내기
3. 양수도 절댓값이 큰거 끼리 먼저 묶어서 곱을 더하기
4. 1은 무조건 더하는게 이득임 (묶기 x)
이렇게 하기위해 음수랑 양수 따로 받아서 구현했습니다.
```
---
```
일단 각 날짜에서 할 수 있는 최대 w를 두고 시작했습니다 (ex: 1일에는 20, 2일에는 30 .... 4일에는 60)
그리고 예제에서 4일같은 경우 과제가 여러개(60, 40, 10) 있으므로 4일 이전 날짜에서 (40, 10)보다 과제가 없는날이거나 w가 작은 과제를 찾습니다. 
그 중 가장 w가 작은 과제가 있는 날과 대체합니다. (과제가 없는 날이 최우선적으로 대체)
```
---
> 박준형 / 3기 2주차 / 2문제

- yongjun/third/week2/boj_1339.java
- yongjun/third/week2/boj_13904.java
- yongjun/third/week2/boj_2036.java
```
고려해야 할 점이 많았던 문제로 기억합니다.
1을 제외한 양수, 1, 0, 음수 이렇게 분류를 했습니다.
1을 제외한 양수는 모두 곱했고, 남은 숫자는 1과 함께 더하기를 했습니다.
음수는 오름차순으로 정리를 한 뒤, 곱하기를 하고 남은 숫자는 0이 존재한다면 0과 곱해서 없애고,
0없다면 더하기 처리 했습니다.
```
---
```
w를 내림차순으로 정렬 한 뒤, 가장 큰 숫자부터 과제를 할 수 있는 날 중 가장 뒤에 있는 날짜로 배치시키는 전략으로 해결했습니다.
```
---
```
자리수와 10을 곱한 숫자를 입력 받은 숫자와 곱해 배열에 저장했습니다.
이후 배열을 정렬하고 9부터 1까지 순서대로 곱해 답을 구했습니다.
```
> 홍용준 / 3기 2주차 / 3문제

- leeYuSung/BOJ/BOJ2036.java
```
처음 문제를 풀었을 때에는 main 함수에 여러 if문을 주어 문제를 해결했습니다. 문제에 있는 테스트 케이스와 제가 따로 만든 테스트 케이스는 해결하였지만 계속 틀렸다고 나와 지금과 같은 방식으로 문제를 해결하였습니다.
1. 제가 문제를 풀 때 가장 많이 고려한 것은 0과 1입니다. 
2. 만약 음수가 홀수 개가 있는데 0이 있다면 남는 음수에 0을 곱했습니다.
3. 양수에서는 1을 곱하는 상황이라면 1을 더하는 방식으로 문제를 해결하였습니다.
---
> 이유성 / 3기 2주차 / 1문제

- yongjun/third/week3/boj_1520.java
- yongjun/third/week3/boj_15989.java
- yongjun/third/week3/swea_9780.java
```
case[i] = case[i - 3] + i / 2 + 1 이라는 점화식을 통해 풀었습니다. 
```
---
```
array[i] = Math.max(Current Number + array[i - 2], array[i - 1]);
바로 옆에 있는 숫자와는 더하지 못하므로 자신의 전 값과, 자신과 두 칸 전에 있는 값의 최대 값을 구해 해결했습니다. 
```
---
```
문제가 어렵네요,,,
정답을 참고해 풀었습니다.
isVisited[y][x] += dfs(ny, nx); 이런 식을 통해 경우의 수를 구했습니다.
```
> 홍용준 / 3기 3주차 / 3문제

- choidonghyeon/java2/boj/BOJ123더하기4.java
- choidonghyeon/java2/boj/내리막길.java
- choidonghyeon/java2/boj/외계인침공.java
풀이가 직관적으로 떠오르지않아 다른 사람의 코드를 참고했습니다.
dp 문제를 풀때 단순히 점화식을 찾는 습관이 있었는데 이 문제처럼 순서를 정해서 흐름을 제어하는 것도 가능하단 걸 알게됐습니다.
---
문제는 장황하지만 i-1과 i-2번 을 비교하면 되는 문제였습니다.
왜인지는 모르겠지만 분명 로직자체는 다른 코드와 동일한데 테케가 계속 하나 틀리네요..
---
dfs와 dp가 혼잡된 문제여서 생각할 거리가 많았던 문제였습니다. 처음에 문제 풀땐 dfs메서드를 비효율적으로 작성해서 코드가 길었었는데 어느정도 정리한 후 코드도 짧아지고 전체적으로 가독성이 좋아진것같습니다.
> 최동현 / 3기 3주차 / 3문제

- leeYuSung/BOJ/BOJ1520.java
- leeYuSung/BOJ/BOJ15989.java
```
깊이 우선 탐색을 활용하여 내리막길로 가는 경로를 구함
탐색이 완료된 점은 dp를 사용하여 경로의 개수를 저장하고 다른 점에서 탐색이 되었을 때에는 이 점을 더해주는 방식으로 
```
---
```
이 문제는 점화식을 이용하여 해결하였습니다.
먼저  dp의 초기값을 설정해주었습니다.
그 후 3을 주기로 점화식을 활용하여 해결하였습니다.
```
---
2주차와 3주차에 일정이 너무 많아서 잘 하지 못하였습니다.
다음주차부터는 다시 열심히 하겠습니다!
> 이유성 / 3기 3주차 /2문제

- junhyeong/week-3/src/BOJ1520.java
- junhyeong/week-3/src/BOJ15989.java
- junhyeong/week-3/src/SWEA_9780.java
```
어려웠습니다,, 점화식을 도저히 못찾겠어서 다른 사람의 코드를 참고했습니다. 
i -1 은 1로 끝난 것들을 더하고
i - 2는 1하고 2로 끝난 것을 더하고 
i - 3 은 1하고 2하고 3으로 끝난 것을 더하는 방식의 풀이입니다.
https://velog.io/@jkh9615/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EB%B0%B1%EC%A4%80-15989-1-2-3-%EB%8D%94%ED%95%98%EA%B8%B0-4-Java
```
---
```
문제 자체 식을 구하는 건 쉬웠지만 예외가 어려웠습니다. 문제는 max(dp[i - 2] + arr[i], dp[i-1]) 의 점화식으로 푸는 문제였습니다. 처음에 dp[] 배열로 했었는데 메모리초과가 떠서 변수로 바꾸었습니다. 그래도 테케 몇개가 틀려서 그 변수들을 long 자료형으로 바꾸니 저는 다 통과할 수 있었어요.
```
---
```
처음에 dp + bfs로 풀려고 했는데 메모리 초과가 떴씁니다. 그래서 몇 시간 더 해보다가 포기하고 다른 사람 코드를 참고하게 되었습니다. dfs로 바꾸니 성공할 수 있었네요
```
> 박준형 / 3기 3주차 / 3문제 

- kimyeonsup/baekjoon/OneTwoThreeFour.java
- kimyeonsup/baekjoon/내리막길.java
- kimyeonsup/samsung/외계인침공.java
> 시간 복잡도 : O(n) , 공간 복잡도 : 
문제 요구사항은 개구리를 납치할 수 있는 최대 값입니다. 즉 모든 경우의 수를 탐색해야하는데 입력 값의 범위를 생각하면 최적화가 필요한 문제입니다. 그렇기 때문에 DP문제라는 것을 유추해볼 수 있습니다. 또는 이분탐색으로 최적화할 수도 있다고 합니다.
DP로 생각한 풀이는 다음과 같습니다.
가장 중요한 것은 침공을 하게되면 침공한 나라 +-1 주변 나라는 침공해도 납치할 수 없다는 조건이 입니다. 
이는 i를 침공하면 최소 i + 1는 침공할 수 없다는 얘기입니다. 또는 i를 선택안하면 i+1은 침공할 수 있습니다.
그렇게 생각해서 점화식을 유추해보면 dp[i - 2] + dp[i] 이거나 dp[i-1] 둘 중 하나를 선택할 수 있습니다.
```
dp[n] =  max(dp[i -2] + arr[i],  dp[i-1])
```
위와 같은 점화식을 세울 수 있었습니다.
---
> 시간 복잡도 :   , 공간 복잡도 : 
DFS와 dp를 사용해 최적화해서 문제를 풀었습니다.
dfs만으로는 모든 방향을 탐색하기엔 불가능 합니다. 그렇기  때문에 dp를 사용하여 이전에 탐색했던  경로를 저장하도록 문제를 풀었습니다.
---
> 시간 복잡도 :   , 공간 복잡도 : 
다른 사람 풀이를 보고 문제를 풀었습니다.
문제 풀이는 다음과 같습니다.
더하기 가장 끝에 있는 숫자가 1이 되거나 2,3이 되어 숫자 n을 만들 수 있는 경우의 수를 저장하고 다음 n을 구할 때 이전 갯수를 사용했습니다.
```
dp[i][1] = dp[i - 1][1];
dp[i][2] = dp[i …
```
> 김연섭 / 3기 3주차 / 3문제

- leeYuSung/BOJ/BOJ15686.java
- leeYuSung/BOJ/BOJ1759.java
```
백트랙킹을 활용하여 문제를 구현하였습니다
갯수에 맞게 알파뱃을 넣은 후에 그것이 모음>=1 자음 >=2 조건에 맞는다면 출력하도록 구현하였습니다
```
---
```
백트랙킹을 활용하여 오픈 가능한 치킨집의 수만큼을 계산하고 이를 이용하여 가장 최소의 거리가 나올 수 있도록 구현하였습니다.
```
---
> 이유성 /4주차 /2문제

- sanghwa/BOJ/ChickenDelivery.java
- sanghwa/BOJ/CreatePassword.java
```
들어온 문자들을 정렬한 후에 진행합니다.
배열에 암호문 길이까지 문자를 추가합니다.
암호문의 유효성을 검사한 후에 재귀를 탈출하면 마지막에 넣은 문자를 제거합니다.
다음 문자를 추가해서 재귀를 진행합니다.
```
---
```
최종적으로 블로그를 참고 했습니다.
M개의 치킨집을 조합하며 모든 치킨 거리의 합 중 최소를 구합니다.
```
---
> 이상화 / 4주차 / 2문제

- yongjun/third/week4/소문난_칠공주.java
- yongjun/third/week4/암호만들기.java
- yongjun/third/week4/치킨_배달.java
오늘 시간이 없어 주말 내로 채워놓겠습니다. 
```
```
---
```
```
---
> 홍용준 / 4주차 /3문제

- choidonghyeon/java2/boj/소문난_칠공주.java
- choidonghyeon/java2/boj/암호만들기.java
- choidonghyeon/java2/boj/치킨배달.java
풀이가 직관적으로 떠오르지 않아 다른사람의 풀이를 참고했습니다.
이 문제에서 백트래킹을 사용하는 핵심은 `조합`이였던것 같아요. 최악의 경우를 어림잡아 계산해봐도 가능한 모든 경우의 수가 
최악의경우에도 40만정도 밖에 되지 않아서 모든 경우의수를 백트래킹으로 구하고, 조건에 만족하는지 판단하면 되는 문제였던것 같아요.
사실 이 부분에서도 `(y,x)` 에 해당하는 좌표를 임의의 수를 부여해서 좀 더 직관적으로 사용하는 테크닉도 필요했고,
경우의 수가 조건에 부합하는 형태인지 확인하는 과정도 `bfs`를 활용해야해서 어려운 문제였던 같습니다.
혼자 힘으로 풀지 못해 좀 아쉬웠습니다.
---
모든 문자를 오름차순으로 정렬 후,
모든 경우의 수를 백트래킹으로 찾아가며 특정 길이에 도달하면
자음과 모음의 개수를 카운트해서 조건에 만족하는지 판별하는 식으로 진행했습니다.
---
치킨집과 집을 각각 리스트 형태로 저장하고,
치킨집을 주어진 개수에 맞게 선택(조합)하는 모든 경우의 수에 대해
각 집에서 선택된 치킨 집들까지의 최단거리를 갱신해 나갔습니다.
시간복잡도를 줄일 수 있는 가장 최선의 방법은
각 집에서 치킨 집까지의 거리를 모두 계산하여 메모이제이션해놓고
동일한 계산의 반복을 최대한 줄일 수있습니다.
> 최동현 / 4주차 / 3문제

- junhyeong/week-4/src/BOJ1941.java
```
+ 모양과 같이 수직인 경우도 생길 수 있어서 dfs 탐색으로는  풀지 못하는 문제였습니다.
그래서 21C7 경우의 수를 모두 대조해보면서 bfs로 7개가 모두 이어져 있는지 확인했습니다.
```
---
이번주 토이프로젝트 2개를 같이하다보니 바빴네요.. 다음주는 더 열심히 풀겠습니다!
> 박준형 / 4주차 / 1문제

- kimyeonsup/baekjoon/Boj_15686.java
- kimyeonsup/baekjoon/Boj_1759.java
폐업시키지 않을 치킨집을 m개 고른 후 (백트래킹) 치킨과 집 사이의 거리 중 가장 작은 거리를 합하는 방식으로 풀었습니다.
결국 치킨집과 집에 위치만 알면 되기 때문에 List에 따로 담아서 탐색하도록 구현했습니다.
---
백트래킹과 문자 조합으로 풀었습니다. 알파 벳 순서대로 탐색하면 되기 때문에 정렬 후 조건에 맞는 가능한 조합을 모두 출력하는 방식으로 풀었습니다. 문제에 조건인 모음 하나 자음 2개만 부합하면 어렵지 않게 풀 수 있는 문제인 것 같습니다.
---
풀지 못했습니다. 풀고 난 후 다시 리뷰하겠습니다.
> 김연섭 / 4주차 / 2문제

- choidonghyeon/java2/boj/스카이라인_쉬운거.java
- choidonghyeon/java2/boj/크게만들기.java
- choidonghyeon/java2/pgs/주식가격.java
```
1. 스택에 아무것도 없으면 숫자를 push한다.
2. 그외의경우 스택 peek을 하여 작으면 pop한다. while로 가능할때까지 반복한다.
3. stack에 담겨있는 문자들을 문제에서 요구하는 길이에맞게 역순으로 꺼낸다.
```
---
stack에는 아직 가격이 하락하지 않은 시점들만 존재하고, 시점은 인덱스와 주식가격으로 이루어져있습니다.
인덱스를 1씩 증가시켜가며 스택의 시점들의 주식가격과 현재가격을 비교하여 pop하고 각 시점까지의 경과시간을 갱신했습니다.
---
얼핏보면 어려워보였지만 고도가 낮아질때마다 빌딩의 수를 하나씩 추가 시켜나간다는 생각으로 해결했습니다.
예외 상황으로 고도가 0인경우로 변화하는 경우만 고려해주면되었습니다.
> 최동현 / 5주차 / 3문제

- kimyeonsup/baekjoon/크게만들기.java
- kimyeonsup/programmers/주식가격.java
문제를 보면 N-K 자리의 가장 큰 수를 만들어주면 됩니다. 그리고 k개를 뺄 때 까지 작은 수를 빼주고 큰 수들을 앞 자리에 채워주면 가장 큰 수가 만들어지게 됩니다.
그래서 주어진 숫자를 순회하면서 Stack에 담아주고 이 때 다음 수가 이전 수 보다 크면 Stack에 들어가 있는 숫자를 빼고 큰 수를 넣어 줍니다. 그리고 k개를 감소 시킵니다. 그리고 이미 들어가있는 수가 더 크다면 다음 수로 넘어갑니다.
이렇게 k개를 뺄 때 까지 앞자리에 큰 수를 만들어 주고 나머지 자리는 순서대로 넣어주어 문제를 풀었습니다.
---
완전 탐색으로 풀었습니다. prices를 2중 for문으로 탐색하며 각 주식 가격의 시간을 계산했습니다.
prices의 길이가 10만이긴 하지만 문제 특성상 주식가격이 떨어지는 조건이 되면 탐색을 멈추기 때문에 크게 걸리지 않을 것 같아 완전탐색으로 풀었습니다.
---
> 김연섭 / 3기 5주차 / 2문제

- junhyeong/week-5/src/BOJ2812.java
- junhyeong/week-5/src/PGS_StockPrice.java
```
스택에 값을 넣을때마다 스택 too 값과 비교해서 top이 더 크거나 같을 때까지 스택을 빼서 넣는다.
뺄때마다 `k--` 해줘서 k가 0이면 그만 빼도록 한다.
그러면 앞쪽에는 올 수 있는 가장 큰값이 배치되기때문에 큰값이 만들어진다.
```
---
```
단순히 더 낮은값이 나오면 반복문을 나오고 cnt를 기록한다.
```
---
> 박준형 / 5주차 / 2문제

- leeYuSung/BOJ/BOJ1759.java
- leeYuSung/BOJ/BOJ1863.java
- leeYuSung/BOJ/BOJ2812.java
- leeYuSung/PGS/PGSStockPrice.java
```
https://velog.io/@dldbtjd14742/BOJ-2812-%ED%81%AC%EA%B2%8C-%EB%A7%8C%EB%93%A4%EA%B8%B0-%EA%B3%A8%EB%93%9C3
```
---
```
https://velog.io/@dldbtjd14742/BOJ-1863-%EC%8A%A4%EC%B9%B4%EC%9D%B4%EB%9D%BC%EC%9D%B8-%EC%89%AC%EC%9A%B4%EA%B1%B0-%EA%B3%A8%EB%93%9C4
```
---
```
자신보다 낮은 가격이 나올 때까지의 시간을 구함
```
> 이유성 / 5주차 / 3문제

- leeYuSung/BOJ/BOJ1766.java
- leeYuSung/BOJ/BOJ2109.java
- leeYuSung/PGS/PGSMoreHot.java
```
https://velog.io/@dldbtjd14742/BOJ-2109-%EC%88%9C%ED%9A%8C%EA%B0%95%EC%97%B0-%EA%B3%A8%EB%93%9C3
```
---
```
https://velog.io/@dldbtjd14742/BOJ-1766-%EB%AC%B8%EC%A0%9C%EC%A7%91-%EA%B3%A8%EB%93%9C2
```
---
```
우선순위 큐를 사용하여 문제를 해결함
```
> 이유성 / 3기 6주차/ 3문제

- leeYuSung/BOJ/BOJ15483.java
```
dp 배열을 구현할 때 앞에 공백을 추가하여 검사해야하기 때문에 크기를 +1로 하였습니다
그 후 배열을 초기화 시키고
이중for문을 활용하여 경우에 따른 검사를 진행하였습니다
제가 아직 dp문제를 잘 풀지 못하여 고민을 해보았지만 풀지 못해 정답을 보고 풀었습니다
진행하던 프로젝트가 어제 마무리되어서 다 풀지 못하였습니다! 다음주부터 다시 열심히 풀겠습니다!
```
> 이유성 / 4기 1주차/ 1문제

- junhyeong/4기/week-01/BOJ15483.java
- junhyeong/4기/week-01/BOJ17208.java
```
https://hooongs.tistory.com/299 
점화식 참고함
```
---
```
dp를 3차원 배열로 만들었습니다. dp[주문][남은 버거 수][남은 감튀 수] 
그리고 점화식에 따라 dp 진행
```
---
> 박준형 / 4기 1주차 / 2문제

- junghyunwoo/4th/week1/BOJ15483_최소편집.java
- junghyunwoo/4th/week1/BOJ17208_카우버거알바생.java
> 시간 복잡도 : O(N^2) , 공간 복잡도 : O(N)
```
- 92 ms
- DP
- dp[i][j]
- = B의 i 번째, A의 j 번째 문자까지의 prefix로 계산된 최소 편집 횟수
- dp[0][i] = i, dp[i][0] = i
- B[i] == A[j]이면
-   dp[i][j] = dp[i - 1][j - 1]
- B[i] != A[j]이면
-   dp[i][j] = min(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]) + 1
- dp[i]가 dp[i - 1]까지만 참조하므로 배열 두 개로 재사용
```
---
> 시간 복잡도 : O(NMK) , 공간 복잡도 : O(MK)
```
- 116 ms
- Knapsack
- 용량 (M, K) 가방에
- 무게 (x, y), 가치 1인 N 가지 짐들로 만들 수 있는 최대 가치
- Knapsack 뒤에서부터 탐색 : dp 1차원 줄이기
- dp[i][j] = 용량 (i, j)에 현재까지의 짐들로 만들 수 있는 최대 가치
- dp[i][j] = max(dp[i][j], dp[i - x][j - y] + 1)
```
---
> 정현우 / 4기 1주차 / 2문제

- sanghwa/BOJ/BOJ13424.java
- sanghwa/BOJ/BOJ17140.java
- sanghwa/BOJ/BOJ3584.java
```
구현 문제로 행과 열의 최대 길이를 비교하며 R, C연산을 반복합니다.
compareTo를 오버라이딩하여 cnt가 높은 숫자, 숫자가 큰 순서로 정렬합니다.
```
---
```
다익스트라로 노드간의 이동 비용을 계산 후 각 노드에서 이동 비용이 가장 작은 방번호를 출력합니다.
```
---
```
자식에서 부모로 단방향 배열로 저장합니다.
첫 번째 자식노드에서 부모를 순회하면 visited처리합니다.
두 번째 자식노드에서 부모를 순회하며 visited처리된 부모를 만나면 부모 노드번호를 출력합니다.
```
---
> 이상화 / 4기 2주차 / 3문제

- junghyunwoo/4th/week2/BOJ13424_비밀모임.java
- junghyunwoo/4th/week2/BOJ17140_이차원배열과연산.java
- junghyunwoo/4th/week2/BOJ3584_가장가까운공통조상.java
> 시간 복잡도 : O(N^2 logN K) , 공간 복잡도 : O(N^2)
```
- 88 ms
- 구현
- 숫자별 등장 횟수 class Count (num, cnt)
- 배열 순회하면서 0이 아니면 해당 숫자의 cnt++
- 처음 방문하는 숫자인 경우 Count 객체 temp 배열에 삽입
- temp 정렬
- temp에서 Count 하나씩, 최대 50개 꺼내면서
- 배열 A에 num, cnt 삽입, cnt와 방문여부 초기화
- 나머지 공간 0으로 초기화
- 숫자가 들어있는 길이 = temp 크기 * 2
- 열의 개수 = 행 최대 길이, 행의 개수 = 열 최대 길이
```
---
> 시간 복잡도 : O(N^3) , 공간 복잡도 : O(N^2)
```
- 200 ms
- 플로이드-워셜
- 모든 노드 간 최단 거리 생성 (플로이드-워셜)
- 각 노드들로부터 친구가 존재하는 노드들까지의
-   거리합이 최소인 노드
```
---
> 시간 복잡도 : O(N) , 공간 복잡도 : O(N)
```
- 168 ms
- 트리
- 첫 번째 노드에서 부모를 따라가면서 루트까지 방문 처리
- 두 번째 노드에서 부모를 따라가다 방문 처리된 노드를 만나면
-   해당 노드가 두 노드의 LCA
```
---
> 정현우 / 4기 2주차 / 3문제

- leeYuSung/BOJ/BOJ1106.java
- leeYuSung/BOJ/BOJ1443.java
https://velog.io/@dldbtjd14742/BOJ-1443-%EB%A7%9D%EA%B0%80%EC%A7%84-%EA%B3%84%EC%82%B0%EA%B8%B0
---
https://velog.io/@dldbtjd14742/BOJ-1106-%ED%98%B8%ED%85%94-%EA%B3%A8%EB%93%9C4
---
> 이유성 / 4기 3주차 / 2문제

- junhyeong/4기/week-03/BOJ1106.java
- junhyeong/4기/week-03/BOJ1443.java
```
- dfs로 모든 계산 값을 탐색
- 탐색하면서 max_int 가 넘으면 그쪽은 더 이상 탐색 x
```
---
```
- cost, people이 있으면
- dp[ i ] = min(dp[ i ], cost + dp[ i - people ]
```
---
> 박준형 / 4기 3주차 / 2문제

- yongjun/fourth/week2/boj_1106.java
- yongjun/fourth/week2/boj_1443.java
```
백트래킹을 적용해 해결했습니다.
가지치기 연산을 통해 연산의 수를 줄였습니다.
```
---
```
0 1 Knapsack 알고리즘을 적용해 ### 풀었습니다.
```
---
> 홍용준 / 4기 2주차 / 2문제

- junghyunwoo/4th/week4/BOJ11066_파일합치기.java
- junghyunwoo/4th/week4/BOJ21923_곡예비행.java
> 시간 복잡도 : O(N^2) , 공간 복잡도 : O(N^2)
```
- 136 ms
- 크누스 최적화
- dp[i][j] : i ~ j - 1 까지 합치는데 필요한 최소비용
- sum[i][j] : i ~ j - 1 까지 소설 장 수 구간 합
- i <= mid <= j 일 때,
-   dp[i][j] = min(dp[i][mid] + dp[mid][j]) + sum[i][j]
- a <= b <= c <= d 일 때,
-   sum[a][c] + sum[b][d] <= sum[a][d] + sum[b][c] 이고,
-   sum[b][c] <= sum[a][d]
- sum[i][j]가 사각 부등식과 단조성을 만족하므로 크누스 최적화
- mids[i][j] : dp[i][j]를 최소로 만드는 mid
- mids[i][j - 1] <= mids[i][j] <= mids[i + 1][j]
```
---
> 시간 복잡도 : O(NM) , 공간 복잡도 : O(NM)
```
- 468 ms
- DP
- up[i][j] : (i, j)에 도착하는 상승비행 최대 점수
- up[i][j] = max(up[i + 1][j], up[i][j - 1]) + map[i][j]
- down[i][j] : (i, j)부터 시작하는 하강비행 최대 점수
- down[i][j] = max(down[i + 1][j], down[i][j + 1]) + map[i][j]
- up[i][j] + down[i][j] 최대값 출력
```
---
> 정현우 / 4기 4주차 / 2문제

- sanghwa/BOJ/곡예 비행.java
- sanghwa/BOJ/파일 합치기.java
> 시간 복잡도 : O(NM)  , 공간 복잡도 : 
```
상승과 하강을 독립적으로 수행합니다.
상승 : 아래, 왼쪽에서 이동한 값중 큰 값으로 저장합니다.
하강 : 오른쪽 맨 아래에서 시작합니다. 아래, 오른쪽에서 이동한 값중 큰 값으로 저장합니다.
두 DP배열의 값을 더한 경우 가장 큰 값으로 출력합니다.
```
---
```
누적합을 밀 계산합니다.
누적합을 통해 i ~ j 사이 파일을 합치는 비용을 계산합니다.
최소 값을 구해 출력합니다.
```
---
> 이상화 / 4기 / 4주차 / 2문제

- choidonghyeon/java2/boj/곡예비행.java
- choidonghyeon/java2/boj/파일합치기.java
```
1. 구간합을 구한다.
2. 특정 방향을 돌며 dp 테이블을 메모라이즈 한다. 이때 미리놓은 구간합을 이용해서 시간을 줄인다.
3. dp[0][n - 1]이 답
```
---
```
1. 상승비행과 하강비행을 각각 나누어서 생각한다.
2. bfs로 이동할때, dp 테이블 따로 만들어 시작 지점에서 해당 지점에 갈 수 있는 최대 값을 구한다.
3. 모든 지점에서 상승비행 dp 테이블과 하강비행 dp 테이블을 더한 값이 가장 큰값이 답으로 선택한다.
```
---
> 최동현 / 4기 4주차 / 2문제
